const fillBlankQuestions = [
  {
    id: "blank-001",
    sentence: "I drink milk every morning.",
    blankSentence: "I drink ___ every morning.",
    answer: "milk",
    acceptableAnswers: ["milk"],
    translation: "我每天早上喝牛奶。",
    explanation: "milk 是初級常見單字，表示牛奶。",
    category: "單字",
    hint: "一種白色飲品",
  },
  {
    id: "blank-002",
    sentence: "She has a small dog.",
    blankSentence: "She has a small ___.",
    answer: "dog",
    acceptableAnswers: ["dog"],
    translation: "她有一隻小狗。",
    explanation: "dog 是常見動物單字，表示狗。",
    category: "單字",
    hint: "會汪汪叫的動物",
  },
  {
    id: "blank-003",
    sentence: "This is my book.",
    blankSentence: "This is my ___.",
    answer: "book",
    acceptableAnswers: ["book"],
    translation: "這是我的書。",
    explanation: "book 表示書，是學校與日常生活常用單字。",
    category: "單字",
    hint: "可以閱讀的東西",
  },
  {
    id: "blank-004",
    sentence: "We eat rice for lunch.",
    blankSentence: "We eat ___ for lunch.",
    answer: "rice",
    acceptableAnswers: ["rice"],
    translation: "我們午餐吃飯。",
    explanation: "rice 表示米飯，是食物類常見單字。",
    category: "單字",
    hint: "常見主食",
  },
  {
    id: "blank-005",
    sentence: "The sky is blue.",
    blankSentence: "The sky is ___.",
    answer: "blue",
    acceptableAnswers: ["blue"],
    translation: "天空是藍色的。",
    explanation: "blue 表示藍色，是基礎顏色單字。",
    category: "單字",
    hint: "天空常見的顏色",
  },
  {
    id: "blank-006",
    sentence: "They play soccer after school.",
    blankSentence: "They ___ soccer after school.",
    answer: "play",
    acceptableAnswers: ["play"],
    translation: "他們放學後踢足球。",
    explanation: "play 可搭配球類運動，例如 play soccer。",
    category: "動詞",
    hint: "做球類運動常用的動詞",
  },
  {
    id: "blank-007",
    sentence: "I read a book at night.",
    blankSentence: "I ___ a book at night.",
    answer: "read",
    acceptableAnswers: ["read"],
    translation: "我晚上讀一本書。",
    explanation: "read 表示閱讀，read a book 是常見用法。",
    category: "動詞",
    hint: "看書時做的動作",
  },
  {
    id: "blank-008",
    sentence: "We eat breakfast at seven.",
    blankSentence: "We ___ breakfast at seven.",
    answer: "eat",
    acceptableAnswers: ["eat", "have"],
    translation: "我們七點吃早餐。",
    explanation: "eat breakfast 表示吃早餐；have breakfast 也常用來表示吃早餐。",
    category: "動詞",
    hint: "吃東西的動作",
  },
  {
    id: "blank-009",
    sentence: "He likes English.",
    blankSentence: "He ___ English.",
    answer: "likes",
    acceptableAnswers: ["likes"],
    translation: "他喜歡英文。",
    explanation: "主詞 He 是第三人稱單數，現在式動詞 like 要加 s，變成 likes。",
    category: "動詞",
    hint: "like 的第三人稱單數現在式",
  },
  {
    id: "blank-010",
    sentence: "My mother cooks dinner.",
    blankSentence: "My mother ___ dinner.",
    answer: "cooks",
    acceptableAnswers: ["cooks"],
    translation: "我媽媽煮晚餐。",
    explanation: "主詞 My mother 是第三人稱單數，現在式動詞 cook 要加 s。",
    category: "動詞",
    hint: "cook 的第三人稱單數現在式",
  },
  {
    id: "blank-011",
    sentence: "She is a student.",
    blankSentence: "She ___ a student.",
    answer: "is",
    acceptableAnswers: ["is"],
    translation: "她是一名學生。",
    explanation: "主詞 She 搭配 be 動詞 is。",
    category: "be 動詞",
    hint: "She 搭配的 be 動詞",
  },
  {
    id: "blank-012",
    sentence: "I am happy.",
    blankSentence: "I ___ happy.",
    answer: "am",
    acceptableAnswers: ["am"],
    translation: "我很開心。",
    explanation: "主詞 I 搭配 be 動詞 am。",
    category: "be 動詞",
    hint: "I 搭配的 be 動詞",
  },
  {
    id: "blank-013",
    sentence: "They are friends.",
    blankSentence: "They ___ friends.",
    answer: "are",
    acceptableAnswers: ["are"],
    translation: "他們是朋友。",
    explanation: "主詞 They 是複數，搭配 be 動詞 are。",
    category: "be 動詞",
    hint: "They 搭配的 be 動詞",
  },
  {
    id: "blank-014",
    sentence: "It is sunny today.",
    blankSentence: "It ___ sunny today.",
    answer: "is",
    acceptableAnswers: ["is"],
    translation: "今天是晴天。",
    explanation: "描述天氣時常用 It is，加上天氣形容詞。",
    category: "be 動詞",
    hint: "It 搭配的 be 動詞",
  },
  {
    id: "blank-015",
    sentence: "You are my teacher.",
    blankSentence: "You ___ my teacher.",
    answer: "are",
    acceptableAnswers: ["are"],
    translation: "你是我的老師。",
    explanation: "主詞 You 搭配 be 動詞 are。",
    category: "be 動詞",
    hint: "You 搭配的 be 動詞",
  },
  {
    id: "blank-016",
    sentence: "The book is on the desk.",
    blankSentence: "The book is ___ the desk.",
    answer: "on",
    acceptableAnswers: ["on"],
    translation: "書在桌子上。",
    explanation: "on 表示在物體表面上。",
    category: "介系詞",
    hint: "表示在上面",
  },
  {
    id: "blank-017",
    sentence: "The cat is under the chair.",
    blankSentence: "The cat is ___ the chair.",
    answer: "under",
    acceptableAnswers: ["under"],
    translation: "貓在椅子下面。",
    explanation: "under 表示在某物下面。",
    category: "介系詞",
    hint: "表示在下面",
  },
  {
    id: "blank-018",
    sentence: "I live in Taipei.",
    blankSentence: "I live ___ Taipei.",
    answer: "in",
    acceptableAnswers: ["in"],
    translation: "我住在台北。",
    explanation: "live in 加上城市或地點，表示住在某地。",
    category: "介系詞",
    hint: "表示在某城市裡",
  },
  {
    id: "blank-019",
    sentence: "She goes to school.",
    blankSentence: "She goes ___ school.",
    answer: "to",
    acceptableAnswers: ["to"],
    translation: "她去學校。",
    explanation: "go to school 表示去上學或去學校。",
    category: "介系詞",
    hint: "go 後面常接的方向介系詞",
  },
  {
    id: "blank-020",
    sentence: "The store is near my house.",
    blankSentence: "The store is ___ my house.",
    answer: "near",
    acceptableAnswers: ["near"],
    translation: "那家商店在我家附近。",
    explanation: "near 表示在附近、靠近。",
    category: "介系詞",
    hint: "表示靠近",
  },
  {
    id: "blank-021",
    sentence: "What is your name?",
    blankSentence: "___ is your name?",
    answer: "What",
    acceptableAnswers: ["what", "What"],
    translation: "你的名字是什麼？",
    explanation: "What 用來詢問事物、名字或內容。",
    category: "疑問詞",
    hint: "詢問什麼",
  },
  {
    id: "blank-022",
    sentence: "Where do you live?",
    blankSentence: "___ do you live?",
    answer: "Where",
    acceptableAnswers: ["where", "Where"],
    translation: "你住在哪裡？",
    explanation: "Where 用來詢問地點。",
    category: "疑問詞",
    hint: "詢問地點",
  },
  {
    id: "blank-023",
    sentence: "Who is that boy?",
    blankSentence: "___ is that boy?",
    answer: "Who",
    acceptableAnswers: ["who", "Who"],
    translation: "那個男孩是誰？",
    explanation: "Who 用來詢問人物。",
    category: "疑問詞",
    hint: "詢問人物",
  },
  {
    id: "blank-024",
    sentence: "When is your birthday?",
    blankSentence: "___ is your birthday?",
    answer: "When",
    acceptableAnswers: ["when", "When"],
    translation: "你的生日是什麼時候？",
    explanation: "When 用來詢問時間。",
    category: "疑問詞",
    hint: "詢問時間",
  },
  {
    id: "blank-025",
    sentence: "How are you?",
    blankSentence: "___ are you?",
    answer: "How",
    acceptableAnswers: ["how", "How"],
    translation: "你好嗎？",
    explanation: "How are you? 是常見問候語。",
    category: "疑問詞",
    hint: "問候近況時使用",
  },
  {
    id: "blank-026",
    sentence: "I eat breakfast in the morning.",
    blankSentence: "I eat breakfast in the ___.",
    answer: "morning",
    acceptableAnswers: ["morning"],
    translation: "我在早上吃早餐。",
    explanation: "in the morning 表示在早上。",
    category: "時間",
    hint: "一天的開始時段",
  },
  {
    id: "blank-027",
    sentence: "We have lunch at noon.",
    blankSentence: "We have lunch at ___.",
    answer: "noon",
    acceptableAnswers: ["noon"],
    translation: "我們中午吃午餐。",
    explanation: "at noon 表示在中午。",
    category: "時間",
    hint: "中午十二點左右",
  },
  {
    id: "blank-028",
    sentence: "I go to bed at night.",
    blankSentence: "I go to bed at ___.",
    answer: "night",
    acceptableAnswers: ["night"],
    translation: "我晚上上床睡覺。",
    explanation: "at night 表示在晚上。",
    category: "時間",
    hint: "一天中天黑後的時間",
  },
  {
    id: "blank-029",
    sentence: "Today is Monday.",
    blankSentence: "Today is ___.",
    answer: "Monday",
    acceptableAnswers: ["monday", "Monday"],
    translation: "今天是星期一。",
    explanation: "Monday 表示星期一，星期名稱首字母通常大寫。",
    category: "時間",
    hint: "一週的第一個上課日",
  },
  {
    id: "blank-030",
    sentence: "My class starts at eight.",
    blankSentence: "My class starts at ___.",
    answer: "eight",
    acceptableAnswers: ["eight", "8"],
    translation: "我的課八點開始。",
    explanation: "eight 表示數字 8；時間也可簡寫成 8。",
    category: "時間",
    hint: "數字 8 的英文",
  },
  {
    id: "blank-031",
    sentence: "I go to school by bus.",
    blankSentence: "I go to school by ___.",
    answer: "bus",
    acceptableAnswers: ["bus"],
    translation: "我搭公車去上學。",
    explanation: "by bus 表示搭公車，是常見交通工具用法。",
    category: "交通",
    hint: "交通工具",
  },
  {
    id: "blank-032",
    sentence: "Tom rides a bike to the park.",
    blankSentence: "Tom rides a ___ to the park.",
    answer: "bike",
    acceptableAnswers: ["bike", "bicycle"],
    translation: "Tom 騎腳踏車去公園。",
    explanation: "bike 和 bicycle 都可以表示腳踏車。",
    category: "交通",
    hint: "兩輪交通工具",
  },
  {
    id: "blank-033",
    sentence: "My father drives a car.",
    blankSentence: "My father drives a ___.",
    answer: "car",
    acceptableAnswers: ["car"],
    translation: "我爸爸開車。",
    explanation: "drive a car 表示開車。",
    category: "交通",
    hint: "常見四輪交通工具",
  },
  {
    id: "blank-034",
    sentence: "We take the train to Tainan.",
    blankSentence: "We take the ___ to Tainan.",
    answer: "train",
    acceptableAnswers: ["train"],
    translation: "我們搭火車去台南。",
    explanation: "take the train 表示搭火車。",
    category: "交通",
    hint: "在鐵軌上行駛的交通工具",
  },
  {
    id: "blank-035",
    sentence: "The bus stop is near the school.",
    blankSentence: "The ___ stop is near the school.",
    answer: "bus",
    acceptableAnswers: ["bus"],
    translation: "公車站在學校附近。",
    explanation: "bus stop 表示公車站。",
    category: "交通",
    hint: "bus stop 的第一個字",
  },
  {
    id: "blank-036",
    sentence: "I brush my teeth every day.",
    blankSentence: "I brush my ___ every day.",
    answer: "teeth",
    acceptableAnswers: ["teeth"],
    translation: "我每天刷牙。",
    explanation: "brush my teeth 表示刷牙，teeth 是 tooth 的複數。",
    category: "日常生活",
    hint: "刷牙時清潔的部位",
  },
  {
    id: "blank-037",
    sentence: "She washes her hands before dinner.",
    blankSentence: "She washes her ___ before dinner.",
    answer: "hands",
    acceptableAnswers: ["hands"],
    translation: "她晚餐前洗手。",
    explanation: "wash hands 表示洗手，是日常生活常用語。",
    category: "日常生活",
    hint: "吃飯前常清洗的身體部位",
  },
  {
    id: "blank-038",
    sentence: "We watch TV after dinner.",
    blankSentence: "We watch ___ after dinner.",
    answer: "TV",
    acceptableAnswers: ["tv", "TV", "television"],
    translation: "我們晚餐後看電視。",
    explanation: "watch TV 表示看電視；TV 也可以寫成 television。",
    category: "日常生活",
    hint: "晚餐後常看的家電或節目",
  },
  {
    id: "blank-039",
    sentence: "I do my homework after school.",
    blankSentence: "I do my ___ after school.",
    answer: "homework",
    acceptableAnswers: ["homework"],
    translation: "我放學後做作業。",
    explanation: "do my homework 表示做我的作業。",
    category: "日常生活",
    hint: "學生放學後要完成的功課",
  },
  {
    id: "blank-040",
    sentence: "He cleans his room on Saturday.",
    blankSentence: "He cleans his ___ on Saturday.",
    answer: "room",
    acceptableAnswers: ["room"],
    translation: "他星期六打掃他的房間。",
    explanation: "clean one's room 表示打掃某人的房間。",
    category: "日常生活",
    hint: "睡覺或讀書的房間",
  },
  {
    id: "blank-041",
    sentence: "I eat an apple after lunch.",
    blankSentence: "I eat an ___ after lunch.",
    answer: "apple",
    acceptableAnswers: ["apple"],
    translation: "我午餐後吃一顆蘋果。",
    explanation: "apple 是常見水果單字，母音開頭前可用 an。",
    category: "單字",
    hint: "一種常見水果",
  },
  {
    id: "blank-042",
    sentence: "She reads a story after dinner.",
    blankSentence: "She reads a ___ after dinner.",
    answer: "story",
    acceptableAnswers: ["story"],
    translation: "她晚餐後讀一個故事。",
    explanation: "story 表示故事，是初級常見閱讀相關單字。",
    category: "單字",
    hint: "可以被閱讀的短篇內容",
  },
  {
    id: "blank-043",
    sentence: "My brother has a pencil.",
    blankSentence: "My brother has a ___.",
    answer: "pencil",
    acceptableAnswers: ["pencil"],
    translation: "我哥哥有一枝鉛筆。",
    explanation: "pencil 表示鉛筆，是常見文具單字。",
    category: "單字",
    hint: "寫字用的文具",
  },
  {
    id: "blank-044",
    sentence: "We see many birds in the tree.",
    blankSentence: "We see many ___ in the tree.",
    answer: "birds",
    acceptableAnswers: ["birds"],
    translation: "我們看到樹上有許多鳥。",
    explanation: "birds 是 bird 的複數，表示許多鳥。",
    category: "單字",
    hint: "會飛的動物複數",
  },
  {
    id: "blank-045",
    sentence: "The baby drinks water.",
    blankSentence: "The baby drinks ___.",
    answer: "water",
    acceptableAnswers: ["water"],
    translation: "那個嬰兒喝水。",
    explanation: "water 表示水，是不可數名詞。",
    category: "單字",
    hint: "透明的飲品",
  },
  {
    id: "blank-046",
    sentence: "I study English every day.",
    blankSentence: "I ___ English every day.",
    answer: "study",
    acceptableAnswers: ["study"],
    translation: "我每天讀英文。",
    explanation: "study 表示讀書、學習，study English 是常見用法。",
    category: "動詞",
    hint: "學習功課的動作",
  },
  {
    id: "blank-047",
    sentence: "They walk to school.",
    blankSentence: "They ___ to school.",
    answer: "walk",
    acceptableAnswers: ["walk"],
    translation: "他們走路去學校。",
    explanation: "walk 表示走路，主詞 They 用原形動詞。",
    category: "動詞",
    hint: "不用交通工具時的移動方式",
  },
  {
    id: "blank-048",
    sentence: "We listen to music at night.",
    blankSentence: "We ___ to music at night.",
    answer: "listen",
    acceptableAnswers: ["listen"],
    translation: "我們晚上聽音樂。",
    explanation: "listen to music 表示聽音樂，listen 後常接 to。",
    category: "動詞",
    hint: "用耳朵聽的動作",
  },
  {
    id: "blank-049",
    sentence: "He watches TV on Sunday.",
    blankSentence: "He ___ TV on Sunday.",
    answer: "watches",
    acceptableAnswers: ["watches"],
    translation: "他星期日看電視。",
    explanation: "主詞 He 是第三人稱單數，watch 要加 es 變成 watches。",
    category: "動詞",
    hint: "watch 的第三人稱單數現在式",
  },
  {
    id: "blank-050",
    sentence: "Mary sings a song in class.",
    blankSentence: "Mary ___ a song in class.",
    answer: "sings",
    acceptableAnswers: ["sings"],
    translation: "Mary 在課堂上唱一首歌。",
    explanation: "主詞 Mary 是第三人稱單數，sing 要加 s。",
    category: "動詞",
    hint: "sing 的第三人稱單數現在式",
  },
  {
    id: "blank-051",
    sentence: "My parents are busy today.",
    blankSentence: "My parents ___ busy today.",
    answer: "are",
    acceptableAnswers: ["are"],
    translation: "我父母今天很忙。",
    explanation: "My parents 是複數主詞，be 動詞要用 are。",
    category: "be 動詞",
    hint: "複數主詞常用的 be 動詞",
  },
  {
    id: "blank-052",
    sentence: "This bag is heavy.",
    blankSentence: "This bag ___ heavy.",
    answer: "is",
    acceptableAnswers: ["is"],
    translation: "這個袋子很重。",
    explanation: "This bag 是單數主詞，現在式 be 動詞用 is。",
    category: "be 動詞",
    hint: "單數物品常用的 be 動詞",
  },
  {
    id: "blank-053",
    sentence: "We are classmates.",
    blankSentence: "We ___ classmates.",
    answer: "are",
    acceptableAnswers: ["are"],
    translation: "我們是同班同學。",
    explanation: "主詞 We 搭配 be 動詞 are。",
    category: "be 動詞",
    hint: "We 搭配的 be 動詞",
  },
  {
    id: "blank-054",
    sentence: "The flowers are beautiful.",
    blankSentence: "The flowers ___ beautiful.",
    answer: "are",
    acceptableAnswers: ["are"],
    translation: "這些花很漂亮。",
    explanation: "The flowers 是複數主詞，be 動詞用 are。",
    category: "be 動詞",
    hint: "複數名詞搭配的 be 動詞",
  },
  {
    id: "blank-055",
    sentence: "It is cold in winter.",
    blankSentence: "It ___ cold in winter.",
    answer: "is",
    acceptableAnswers: ["is"],
    translation: "冬天天氣很冷。",
    explanation: "描述天氣或季節狀況時常用 It is。",
    category: "be 動詞",
    hint: "It 搭配的 be 動詞",
  },
  {
    id: "blank-056",
    sentence: "I can ride a bike.",
    blankSentence: "I ___ ride a bike.",
    answer: "can",
    acceptableAnswers: ["can"],
    translation: "我會騎腳踏車。",
    explanation: "can 表示會、能夠，後面接原形動詞。",
    category: "助動詞",
    hint: "表示能力的助動詞",
  },
  {
    id: "blank-057",
    sentence: "You must not run here.",
    blankSentence: "You ___ not run here.",
    answer: "must",
    acceptableAnswers: ["must"],
    translation: "你不可以在這裡跑。",
    explanation: "must not 表示禁止或不可以。",
    category: "助動詞",
    hint: "表示規定或禁止的助動詞",
  },
  {
    id: "blank-058",
    sentence: "May I use your pen?",
    blankSentence: "___ I use your pen?",
    answer: "May",
    acceptableAnswers: ["may", "May"],
    translation: "我可以用你的筆嗎？",
    explanation: "May I...? 是禮貌地請求允許的句型。",
    category: "助動詞",
    hint: "禮貌請求允許時常用",
  },
  {
    id: "blank-059",
    sentence: "He cannot swim.",
    blankSentence: "He ___ swim.",
    answer: "cannot",
    acceptableAnswers: ["cannot", "can't", "cant"],
    translation: "他不會游泳。",
    explanation: "cannot 和 can't 都表示不能或不會。",
    category: "助動詞",
    hint: "can 的否定形式",
  },
  {
    id: "blank-060",
    sentence: "We should clean our classroom.",
    blankSentence: "We ___ clean our classroom.",
    answer: "should",
    acceptableAnswers: ["should"],
    translation: "我們應該打掃教室。",
    explanation: "should 表示應該，後面接原形動詞。",
    category: "助動詞",
    hint: "表示應該的助動詞",
  },
  {
    id: "blank-061",
    sentence: "The ball is in the box.",
    blankSentence: "The ball is ___ the box.",
    answer: "in",
    acceptableAnswers: ["in"],
    translation: "球在盒子裡。",
    explanation: "in 表示在某物裡面。",
    category: "介系詞",
    hint: "表示在裡面",
  },
  {
    id: "blank-062",
    sentence: "I go to school by bus.",
    blankSentence: "I go to school ___ bus.",
    answer: "by",
    acceptableAnswers: ["by"],
    translation: "我搭公車去上學。",
    explanation: "by bus 表示搭公車，交通工具前常用 by。",
    category: "介系詞",
    hint: "交通工具前常用的介系詞",
  },
  {
    id: "blank-063",
    sentence: "She sits next to me.",
    blankSentence: "She sits next ___ me.",
    answer: "to",
    acceptableAnswers: ["to"],
    translation: "她坐在我旁邊。",
    explanation: "next to 表示在旁邊，是常見位置用法。",
    category: "介系詞",
    hint: "next 後面的介系詞",
  },
  {
    id: "blank-064",
    sentence: "The library is across from the park.",
    blankSentence: "The library is across ___ the park.",
    answer: "from",
    acceptableAnswers: ["from"],
    translation: "圖書館在公園對面。",
    explanation: "across from 表示在對面。",
    category: "介系詞",
    hint: "across 後面常接的介系詞",
  },
  {
    id: "blank-065",
    sentence: "We meet at the station.",
    blankSentence: "We meet ___ the station.",
    answer: "at",
    acceptableAnswers: ["at"],
    translation: "我們在車站見面。",
    explanation: "at 可表示在某個明確地點。",
    category: "介系詞",
    hint: "表示在某個地點",
  },
  {
    id: "blank-066",
    sentence: "Why are you late?",
    blankSentence: "___ are you late?",
    answer: "Why",
    acceptableAnswers: ["why", "Why"],
    translation: "你為什麼遲到？",
    explanation: "Why 用來詢問原因。",
    category: "疑問詞",
    hint: "詢問原因的疑問詞",
  },
  {
    id: "blank-067",
    sentence: "Which color do you like?",
    blankSentence: "___ color do you like?",
    answer: "Which",
    acceptableAnswers: ["which", "Which"],
    translation: "你喜歡哪一個顏色？",
    explanation: "Which 用來詢問哪一個。",
    category: "疑問詞",
    hint: "詢問哪一個",
  },
  {
    id: "blank-068",
    sentence: "What time is it?",
    blankSentence: "___ time is it?",
    answer: "What",
    acceptableAnswers: ["what", "What"],
    translation: "現在幾點？",
    explanation: "What time is it? 是詢問時間的常用句型。",
    category: "疑問詞",
    hint: "問時間時常用的疑問詞",
  },
  {
    id: "blank-069",
    sentence: "How old are you?",
    blankSentence: "How ___ are you?",
    answer: "old",
    acceptableAnswers: ["old"],
    translation: "你幾歲？",
    explanation: "How old 用來詢問年齡。",
    category: "疑問詞",
    hint: "詢問年齡時接在 How 後面",
  },
  {
    id: "blank-070",
    sentence: "Who is your English teacher?",
    blankSentence: "___ is your English teacher?",
    answer: "Who",
    acceptableAnswers: ["who", "Who"],
    translation: "誰是你的英文老師？",
    explanation: "Who 用來詢問人物。",
    category: "疑問詞",
    hint: "詢問人物的疑問詞",
  },
  {
    id: "blank-071",
    sentence: "We go home at five o'clock.",
    blankSentence: "We go home at five ___.",
    answer: "o'clock",
    acceptableAnswers: ["o'clock", "oclock"],
    translation: "我們五點回家。",
    explanation: "o'clock 用在整點時間後面，也可寫成 oclock 方便輸入。",
    category: "時間",
    hint: "整點時間常用字",
  },
  {
    id: "blank-072",
    sentence: "School starts in September.",
    blankSentence: "School starts in ___.",
    answer: "September",
    acceptableAnswers: ["september", "September"],
    translation: "學校九月開學。",
    explanation: "September 表示九月，月份名稱首字母通常大寫。",
    category: "時間",
    hint: "一年中的第九個月",
  },
  {
    id: "blank-073",
    sentence: "I play basketball on Friday.",
    blankSentence: "I play basketball on ___.",
    answer: "Friday",
    acceptableAnswers: ["friday", "Friday"],
    translation: "我星期五打籃球。",
    explanation: "Friday 表示星期五，星期名稱首字母通常大寫。",
    category: "時間",
    hint: "星期五的英文",
  },
  {
    id: "blank-074",
    sentence: "We have dinner at six thirty.",
    blankSentence: "We have dinner at six ___.",
    answer: "thirty",
    acceptableAnswers: ["thirty", "30"],
    translation: "我們六點三十分吃晚餐。",
    explanation: "six thirty 表示六點三十分，也可用 30 表示分鐘。",
    category: "時間",
    hint: "表示三十分的英文",
  },
  {
    id: "blank-075",
    sentence: "My birthday is in May.",
    blankSentence: "My birthday is in ___.",
    answer: "May",
    acceptableAnswers: ["may", "May"],
    translation: "我的生日在五月。",
    explanation: "May 表示五月，月份名稱首字母通常大寫。",
    category: "時間",
    hint: "一年中的第五個月",
  },
  {
    id: "blank-076",
    sentence: "She takes the MRT to Taipei.",
    blankSentence: "She takes the ___ to Taipei.",
    answer: "MRT",
    acceptableAnswers: ["mrt", "MRT"],
    translation: "她搭捷運去台北。",
    explanation: "MRT 表示捷運，是台灣常見交通工具。",
    category: "交通",
    hint: "城市中常見的捷運系統",
  },
  {
    id: "blank-077",
    sentence: "I walk to the store.",
    blankSentence: "I ___ to the store.",
    answer: "walk",
    acceptableAnswers: ["walk"],
    translation: "我走路去商店。",
    explanation: "walk 表示走路，也可用在交通方式。",
    category: "交通",
    hint: "不用車時的移動方式",
  },
  {
    id: "blank-078",
    sentence: "The taxi is yellow.",
    blankSentence: "The ___ is yellow.",
    answer: "taxi",
    acceptableAnswers: ["taxi", "cab"],
    translation: "那輛計程車是黃色的。",
    explanation: "taxi 表示計程車；cab 也可表示計程車。",
    category: "交通",
    hint: "可以付費搭乘的車",
  },
  {
    id: "blank-079",
    sentence: "We wait for the bus.",
    blankSentence: "We wait for the ___.",
    answer: "bus",
    acceptableAnswers: ["bus"],
    translation: "我們等公車。",
    explanation: "wait for the bus 表示等公車。",
    category: "交通",
    hint: "在公車站等的交通工具",
  },
  {
    id: "blank-080",
    sentence: "He rides a scooter to work.",
    blankSentence: "He rides a ___ to work.",
    answer: "scooter",
    acceptableAnswers: ["scooter"],
    translation: "他騎機車去上班。",
    explanation: "scooter 表示機車或速克達，是常見交通單字。",
    category: "交通",
    hint: "台灣常見的兩輪機動車",
  },
  {
    id: "blank-081",
    sentence: "I take a shower every night.",
    blankSentence: "I take a ___ every night.",
    answer: "shower",
    acceptableAnswers: ["shower"],
    translation: "我每天晚上洗澡。",
    explanation: "take a shower 表示淋浴、洗澡。",
    category: "日常生活",
    hint: "晚上常做的清潔活動",
  },
  {
    id: "blank-082",
    sentence: "She makes her bed every morning.",
    blankSentence: "She makes her ___ every morning.",
    answer: "bed",
    acceptableAnswers: ["bed"],
    translation: "她每天早上整理床鋪。",
    explanation: "make one's bed 表示整理床鋪。",
    category: "日常生活",
    hint: "睡覺用的家具",
  },
  {
    id: "blank-083",
    sentence: "We eat dinner with our family.",
    blankSentence: "We eat ___ with our family.",
    answer: "dinner",
    acceptableAnswers: ["dinner"],
    translation: "我們和家人一起吃晚餐。",
    explanation: "dinner 表示晚餐，是日常三餐之一。",
    category: "日常生活",
    hint: "晚上的一餐",
  },
  {
    id: "blank-084",
    sentence: "I put on my shoes.",
    blankSentence: "I put on my ___.",
    answer: "shoes",
    acceptableAnswers: ["shoes"],
    translation: "我穿上我的鞋子。",
    explanation: "put on shoes 表示穿上鞋子，shoes 通常用複數。",
    category: "日常生活",
    hint: "穿在腳上的物品",
  },
  {
    id: "blank-085",
    sentence: "He opens the door.",
    blankSentence: "He opens the ___.",
    answer: "door",
    acceptableAnswers: ["door"],
    translation: "他打開門。",
    explanation: "door 表示門，是家中常見物品。",
    category: "日常生活",
    hint: "進出房間會打開的東西",
  },
  {
    id: "blank-086",
    sentence: "I need some sugar.",
    blankSentence: "I need some ___.",
    answer: "sugar",
    acceptableAnswers: ["sugar"],
    translation: "我需要一些糖。",
    explanation: "sugar 表示糖，作為食材時常當不可數名詞。",
    category: "可數不可數",
    hint: "甜的調味品",
  },
  {
    id: "blank-087",
    sentence: "There are three apples on the table.",
    blankSentence: "There are three ___ on the table.",
    answer: "apples",
    acceptableAnswers: ["apples"],
    translation: "桌上有三顆蘋果。",
    explanation: "three 後面接可數名詞複數，所以 apple 要加 s。",
    category: "可數不可數",
    hint: "apple 的複數",
  },
  {
    id: "blank-088",
    sentence: "She has two brothers.",
    blankSentence: "She has two ___.",
    answer: "brothers",
    acceptableAnswers: ["brothers"],
    translation: "她有兩個兄弟。",
    explanation: "two 後面接可數名詞複數，brother 要加 s。",
    category: "可數不可數",
    hint: "brother 的複數",
  },
  {
    id: "blank-089",
    sentence: "I drink a glass of milk.",
    blankSentence: "I drink a glass of ___.",
    answer: "milk",
    acceptableAnswers: ["milk"],
    translation: "我喝一杯牛奶。",
    explanation: "milk 是不可數名詞，可用 a glass of 表示一杯。",
    category: "可數不可數",
    hint: "可用杯子裝的白色飲品",
  },
  {
    id: "blank-090",
    sentence: "There is some bread on the plate.",
    blankSentence: "There is some ___ on the plate.",
    answer: "bread",
    acceptableAnswers: ["bread"],
    translation: "盤子上有一些麵包。",
    explanation: "bread 常作不可數名詞，前面可用 some。",
    category: "可數不可數",
    hint: "常見早餐食物",
  },
  {
    id: "blank-091",
    sentence: "Tom is my brother. He is ten years old.",
    blankSentence: "Tom is my brother. ___ is ten years old.",
    answer: "He",
    acceptableAnswers: ["he", "He"],
    translation: "Tom 是我的哥哥。他十歲。",
    explanation: "Tom 是男生，作主詞時可用代名詞 He。",
    category: "代名詞",
    hint: "男生作主詞時常用",
  },
  {
    id: "blank-092",
    sentence: "Mary is my sister. I like her.",
    blankSentence: "Mary is my sister. I like ___.",
    answer: "her",
    acceptableAnswers: ["her"],
    translation: "Mary 是我的姊妹。我喜歡她。",
    explanation: "Mary 是女生，作受詞時可用 her。",
    category: "代名詞",
    hint: "女生作受詞時常用",
  },
  {
    id: "blank-093",
    sentence: "My dog is cute. It is small.",
    blankSentence: "My dog is cute. ___ is small.",
    answer: "It",
    acceptableAnswers: ["it", "It"],
    translation: "我的狗很可愛。牠很小。",
    explanation: "動物或事物作主詞時常可用 It。",
    category: "代名詞",
    hint: "動物或事物作主詞時常用",
  },
  {
    id: "blank-094",
    sentence: "Jack and I are classmates. We study together.",
    blankSentence: "Jack and I are classmates. ___ study together.",
    answer: "We",
    acceptableAnswers: ["we", "We"],
    translation: "Jack 和我是同班同學。我們一起讀書。",
    explanation: "Jack and I 表示我們，作主詞時用 We。",
    category: "代名詞",
    hint: "包含自己和別人時常用",
  },
  {
    id: "blank-095",
    sentence: "The students are here. They are quiet.",
    blankSentence: "The students are here. ___ are quiet.",
    answer: "They",
    acceptableAnswers: ["they", "They"],
    translation: "學生們在這裡。他們很安靜。",
    explanation: "複數的人或物作主詞時可用 They。",
    category: "代名詞",
    hint: "複數主詞常用",
  },
  {
    id: "blank-096",
    sentence: "This is my pencil.",
    blankSentence: "This is ___ pencil.",
    answer: "my",
    acceptableAnswers: ["my"],
    translation: "這是我的鉛筆。",
    explanation: "my 表示我的，後面接名詞。",
    category: "所有格",
    hint: "表示我的",
  },
  {
    id: "blank-097",
    sentence: "That is his bike.",
    blankSentence: "That is ___ bike.",
    answer: "his",
    acceptableAnswers: ["his"],
    translation: "那是他的腳踏車。",
    explanation: "his 表示他的，後面可接名詞。",
    category: "所有格",
    hint: "表示他的",
  },
  {
    id: "blank-098",
    sentence: "This is her bag.",
    blankSentence: "This is ___ bag.",
    answer: "her",
    acceptableAnswers: ["her"],
    translation: "這是她的袋子。",
    explanation: "her 表示她的，後面接名詞。",
    category: "所有格",
    hint: "表示她的",
  },
  {
    id: "blank-099",
    sentence: "Our school is big.",
    blankSentence: "___ school is big.",
    answer: "Our",
    acceptableAnswers: ["our", "Our"],
    translation: "我們的學校很大。",
    explanation: "Our 表示我們的，放在名詞 school 前面。",
    category: "所有格",
    hint: "表示我們的",
  },
  {
    id: "blank-100",
    sentence: "Their house is near the park.",
    blankSentence: "___ house is near the park.",
    answer: "Their",
    acceptableAnswers: ["their", "Their"],
    translation: "他們的房子在公園附近。",
    explanation: "Their 表示他們的，後面接名詞。",
    category: "所有格",
    hint: "表示他們的",
  },
  {
    id: "blank-101",
    sentence: "I usually eat breakfast at seven.",
    blankSentence: "I ___ eat breakfast at seven.",
    answer: "usually",
    acceptableAnswers: ["usually"],
    translation: "我通常七點吃早餐。",
    explanation: "usually 表示通常，是頻率副詞。",
    category: "頻率副詞",
    hint: "表示通常",
  },
  {
    id: "blank-102",
    sentence: "She never goes to school late.",
    blankSentence: "She ___ goes to school late.",
    answer: "never",
    acceptableAnswers: ["never"],
    translation: "她上學從不遲到。",
    explanation: "never 表示從不，是頻率副詞。",
    category: "頻率副詞",
    hint: "表示從不",
  },
  {
    id: "blank-103",
    sentence: "We often play basketball after school.",
    blankSentence: "We ___ play basketball after school.",
    answer: "often",
    acceptableAnswers: ["often"],
    translation: "我們放學後常常打籃球。",
    explanation: "often 表示常常，是頻率副詞。",
    category: "頻率副詞",
    hint: "表示常常",
  },
  {
    id: "blank-104",
    sentence: "He sometimes reads comics.",
    blankSentence: "He ___ reads comics.",
    answer: "sometimes",
    acceptableAnswers: ["sometimes"],
    translation: "他有時候讀漫畫。",
    explanation: "sometimes 表示有時候，是頻率副詞。",
    category: "頻率副詞",
    hint: "表示有時候",
  },
  {
    id: "blank-105",
    sentence: "They always say thank you.",
    blankSentence: "They ___ say thank you.",
    answer: "always",
    acceptableAnswers: ["always"],
    translation: "他們總是說謝謝。",
    explanation: "always 表示總是，是頻率副詞。",
    category: "頻率副詞",
    hint: "表示總是",
  },
  {
    id: "blank-106",
    sentence: "There are many books in the library.",
    blankSentence: "There are ___ books in the library.",
    answer: "many",
    acceptableAnswers: ["many"],
    translation: "圖書館裡有很多書。",
    explanation: "many 修飾可數名詞複數 books。",
    category: "數量詞",
    hint: "修飾可數名詞複數，表示很多",
  },
  {
    id: "blank-107",
    sentence: "I have some water.",
    blankSentence: "I have ___ water.",
    answer: "some",
    acceptableAnswers: ["some"],
    translation: "我有一些水。",
    explanation: "some 可修飾不可數名詞 water，表示一些。",
    category: "數量詞",
    hint: "表示一些",
  },
  {
    id: "blank-108",
    sentence: "There is a little milk in the cup.",
    blankSentence: "There is ___ little milk in the cup.",
    answer: "a",
    acceptableAnswers: ["a"],
    translation: "杯子裡有一點牛奶。",
    explanation: "a little 修飾不可數名詞，表示一點。",
    category: "數量詞",
    hint: "a little 的第一個字",
  },
  {
    id: "blank-109",
    sentence: "I have a few friends in class.",
    blankSentence: "I have a ___ friends in class.",
    answer: "few",
    acceptableAnswers: ["few"],
    translation: "我班上有幾個朋友。",
    explanation: "a few 修飾可數名詞複數，表示幾個。",
    category: "數量詞",
    hint: "a few 的第二個字",
  },
  {
    id: "blank-110",
    sentence: "Do you have any questions?",
    blankSentence: "Do you have ___ questions?",
    answer: "any",
    acceptableAnswers: ["any"],
    translation: "你有任何問題嗎？",
    explanation: "any 常用在疑問句中，表示任何或一些。",
    category: "數量詞",
    hint: "疑問句中表示任何",
  },
  {
    id: "blank-111",
    sentence: "I like apples and bananas.",
    blankSentence: "I like apples ___ bananas.",
    answer: "and",
    acceptableAnswers: ["and"],
    translation: "我喜歡蘋果和香蕉。",
    explanation: "and 連接兩個並列的事物，表示和。",
    category: "連接詞",
    hint: "表示和",
  },
  {
    id: "blank-112",
    sentence: "I am tired but happy.",
    blankSentence: "I am tired ___ happy.",
    answer: "but",
    acceptableAnswers: ["but"],
    translation: "我很累但是很開心。",
    explanation: "but 表示但是，用來連接相反或轉折的想法。",
    category: "連接詞",
    hint: "表示但是",
  },
  {
    id: "blank-113",
    sentence: "You can have tea or coffee.",
    blankSentence: "You can have tea ___ coffee.",
    answer: "or",
    acceptableAnswers: ["or"],
    translation: "你可以喝茶或咖啡。",
    explanation: "or 表示或者，用來連接選項。",
    category: "連接詞",
    hint: "表示或者",
  },
  {
    id: "blank-114",
    sentence: "I stay home because it is raining.",
    blankSentence: "I stay home ___ it is raining.",
    answer: "because",
    acceptableAnswers: ["because"],
    translation: "因為下雨，所以我待在家。",
    explanation: "because 用來說明原因。",
    category: "連接詞",
    hint: "表示因為",
  },
  {
    id: "blank-115",
    sentence: "Wash your hands before you eat.",
    blankSentence: "Wash your hands ___ you eat.",
    answer: "before",
    acceptableAnswers: ["before"],
    translation: "吃東西前要洗手。",
    explanation: "before 表示在……之前，連接兩個動作。",
    category: "連接詞",
    hint: "表示在之前",
  },
  {
    id: "blank-116",
    sentence: "You can borrow my eraser.",
    blankSentence: "You ___ borrow my eraser.",
    answer: "can",
    acceptableAnswers: ["can"],
    translation: "你可以借我的橡皮擦。",
    explanation: "can 可表示可以或能夠，後面接原形動詞 borrow。",
    category: "助動詞",
    hint: "表示可以的助動詞",
  },
  {
    id: "blank-117",
    sentence: "We must finish our homework.",
    blankSentence: "We ___ finish our homework.",
    answer: "must",
    acceptableAnswers: ["must"],
    translation: "我們必須完成作業。",
    explanation: "must 表示必須，後面接原形動詞 finish。",
    category: "助動詞",
    hint: "表示必須的助動詞",
  },
  {
    id: "blank-118",
    sentence: "May I open the window?",
    blankSentence: "___ I open the window?",
    answer: "May",
    acceptableAnswers: ["may", "May"],
    translation: "我可以打開窗戶嗎？",
    explanation: "May I...? 是禮貌地詢問是否可以做某事的句型。",
    category: "助動詞",
    hint: "禮貌詢問允許時常用",
  },
  {
    id: "blank-119",
    sentence: "She should see a doctor.",
    blankSentence: "She ___ see a doctor.",
    answer: "should",
    acceptableAnswers: ["should"],
    translation: "她應該去看醫生。",
    explanation: "should 表示應該，常用來提出建議。",
    category: "助動詞",
    hint: "表示應該的助動詞",
  },
  {
    id: "blank-120",
    sentence: "I cannot find my key.",
    blankSentence: "I ___ find my key.",
    answer: "cannot",
    acceptableAnswers: ["cannot", "can't", "cant"],
    translation: "我找不到我的鑰匙。",
    explanation: "cannot 和 can't 都表示不能；這裡表示不能找到鑰匙。",
    category: "助動詞",
    hint: "can 的否定形式",
  },
  {
    id: "blank-121",
    sentence: "I wear a hat on sunny days.",
    blankSentence: "I wear a ___ on sunny days.",
    answer: "hat",
    acceptableAnswers: ["hat"],
    translation: "晴天時我戴帽子。",
    explanation: "hat 表示帽子，常戴在頭上遮陽。",
    category: "單字",
    hint: "戴在頭上的東西",
  },
  {
    id: "blank-122",
    sentence: "There is a clock on the wall.",
    blankSentence: "There is a ___ on the wall.",
    answer: "clock",
    acceptableAnswers: ["clock"],
    translation: "牆上有一個時鐘。",
    explanation: "clock 表示時鐘，可用來看時間。",
    category: "單字",
    hint: "牆上看時間的東西",
  },
  {
    id: "blank-123",
    sentence: "My sister draws a flower.",
    blankSentence: "My sister draws a ___.",
    answer: "flower",
    acceptableAnswers: ["flower"],
    translation: "我妹妹畫一朵花。",
    explanation: "flower 表示花，是常見自然單字。",
    category: "單字",
    hint: "植物漂亮的部分",
  },
  {
    id: "blank-124",
    sentence: "Please close the window.",
    blankSentence: "Please close the ___.",
    answer: "window",
    acceptableAnswers: ["window"],
    translation: "請關窗戶。",
    explanation: "window 表示窗戶，是房間裡常見的東西。",
    category: "單字",
    hint: "房間牆上可打開的部分",
  },
  {
    id: "blank-125",
    sentence: "Tom reads a story every night.",
    blankSentence: "Tom ___ a story every night.",
    answer: "reads",
    acceptableAnswers: ["reads"],
    translation: "Tom 每晚讀一個故事。",
    explanation: "主詞 Tom 是第三人稱單數，現在簡單式動詞 read 要加 s。",
    category: "動詞",
    hint: "read 的第三人稱單數",
  },
  {
    id: "blank-126",
    sentence: "They wash the car on Sunday.",
    blankSentence: "They ___ the car on Sunday.",
    answer: "wash",
    acceptableAnswers: ["wash"],
    translation: "他們星期日洗車。",
    explanation: "主詞 They 用原形動詞 wash。",
    category: "動詞",
    hint: "用水清潔",
  },
  {
    id: "blank-127",
    sentence: "My father cooks dinner at home.",
    blankSentence: "My father ___ dinner at home.",
    answer: "cooks",
    acceptableAnswers: ["cooks"],
    translation: "我爸爸在家煮晚餐。",
    explanation: "主詞 My father 是第三人稱單數，cook 要加 s。",
    category: "動詞",
    hint: "準備食物",
  },
  {
    id: "blank-128",
    sentence: "We listen to music after class.",
    blankSentence: "We ___ to music after class.",
    answer: "listen",
    acceptableAnswers: ["listen"],
    translation: "我們下課後聽音樂。",
    explanation: "listen to music 表示聽音樂，主詞 We 用原形動詞。",
    category: "動詞",
    hint: "和 to 搭配，表示聽",
  },
  {
    id: "blank-129",
    sentence: "The boys are in the park.",
    blankSentence: "The boys ___ in the park.",
    answer: "are",
    acceptableAnswers: ["are"],
    translation: "男孩們在公園裡。",
    explanation: "主詞 The boys 是複數，be 動詞要用 are。",
    category: "be 動詞",
    hint: "複數主詞的 be 動詞",
  },
  {
    id: "blank-130",
    sentence: "I am twelve years old.",
    blankSentence: "I ___ twelve years old.",
    answer: "am",
    acceptableAnswers: ["am"],
    translation: "我十二歲。",
    explanation: "主詞 I 的 be 動詞是 am。",
    category: "be 動詞",
    hint: "I 搭配的 be 動詞",
  },
  {
    id: "blank-131",
    sentence: "The soup is hot.",
    blankSentence: "The soup ___ hot.",
    answer: "is",
    acceptableAnswers: ["is"],
    translation: "湯是熱的。",
    explanation: "主詞 The soup 是單數不可數名詞，be 動詞用 is。",
    category: "be 動詞",
    hint: "單數主詞的 be 動詞",
  },
  {
    id: "blank-132",
    sentence: "You are my best friend.",
    blankSentence: "You ___ my best friend.",
    answer: "are",
    acceptableAnswers: ["are"],
    translation: "你是我最好的朋友。",
    explanation: "主詞 You 的 be 動詞用 are。",
    category: "be 動詞",
    hint: "You 搭配的 be 動詞",
  },
  {
    id: "blank-133",
    sentence: "You should drink more water.",
    blankSentence: "You ___ drink more water.",
    answer: "should",
    acceptableAnswers: ["should"],
    translation: "你應該多喝水。",
    explanation: "should 表示應該，後面接原形動詞 drink。",
    category: "助動詞",
    hint: "表示應該",
  },
  {
    id: "blank-134",
    sentence: "Can you help me?",
    blankSentence: "___ you help me?",
    answer: "Can",
    acceptableAnswers: ["Can", "can"],
    translation: "你可以幫我嗎？",
    explanation: "Can you...? 用來詢問對方能不能或可不可以做某事。",
    category: "助動詞",
    hint: "表示可以或能夠",
  },
  {
    id: "blank-135",
    sentence: "We will meet at three.",
    blankSentence: "We ___ meet at three.",
    answer: "will",
    acceptableAnswers: ["will"],
    translation: "我們將在三點見面。",
    explanation: "will 表示未來，後面接原形動詞 meet。",
    category: "助動詞",
    hint: "表示未來",
  },
  {
    id: "blank-136",
    sentence: "She cannot swim fast.",
    blankSentence: "She ___ swim fast.",
    answer: "cannot",
    acceptableAnswers: ["cannot", "can't", "cant"],
    translation: "她不能游得快。",
    explanation: "cannot 和 can't 都表示不能，後面接原形動詞 swim。",
    category: "助動詞",
    hint: "can 的否定形式",
  },
  {
    id: "blank-137",
    sentence: "The dog sleeps under the table.",
    blankSentence: "The dog sleeps ___ the table.",
    answer: "under",
    acceptableAnswers: ["under"],
    translation: "狗睡在桌子下面。",
    explanation: "under 表示在……下面。",
    category: "介系詞",
    hint: "表示在下面",
  },
  {
    id: "blank-138",
    sentence: "I sit beside my brother.",
    blankSentence: "I sit ___ my brother.",
    answer: "beside",
    acceptableAnswers: ["beside", "next to"],
    translation: "我坐在我哥哥旁邊。",
    explanation: "beside 表示在旁邊，也可用 next to 表達。",
    category: "介系詞",
    hint: "表示在旁邊",
  },
  {
    id: "blank-139",
    sentence: "The picture is on the wall.",
    blankSentence: "The picture is ___ the wall.",
    answer: "on",
    acceptableAnswers: ["on"],
    translation: "圖片在牆上。",
    explanation: "on 表示在表面上，圖片掛在牆上用 on。",
    category: "介系詞",
    hint: "表示在表面上",
  },
  {
    id: "blank-140",
    sentence: "We go to school by bus.",
    blankSentence: "We go to school ___ bus.",
    answer: "by",
    acceptableAnswers: ["by"],
    translation: "我們搭公車去上學。",
    explanation: "by bus 表示搭公車，是交通方式的常用說法。",
    category: "介系詞",
    hint: "交通方式前常用",
  },
  {
    id: "blank-141",
    sentence: "Where is your schoolbag?",
    blankSentence: "___ is your schoolbag?",
    answer: "Where",
    acceptableAnswers: ["Where", "where"],
    translation: "你的書包在哪裡？",
    explanation: "Where 用來詢問地點。",
    category: "疑問詞",
    hint: "詢問地點",
  },
  {
    id: "blank-142",
    sentence: "Who is your new class leader?",
    blankSentence: "___ is your new class leader?",
    answer: "Who",
    acceptableAnswers: ["Who", "who"],
    translation: "誰是你的新班長？",
    explanation: "Who 用來詢問人物；這裡詢問新班長是誰。",
    category: "疑問詞",
    hint: "詢問人物",
  },
  {
    id: "blank-143",
    sentence: "Why do you like English?",
    blankSentence: "___ do you like English?",
    answer: "Why",
    acceptableAnswers: ["Why", "why"],
    translation: "你為什麼喜歡英文？",
    explanation: "Why 用來詢問原因；這裡詢問喜歡英文的原因。",
    category: "疑問詞",
    hint: "詢問原因",
  },
  {
    id: "blank-144",
    sentence: "How do you go home?",
    blankSentence: "___ do you go home?",
    answer: "How",
    acceptableAnswers: ["How", "how"],
    translation: "你怎麼回家？",
    explanation: "How 用來詢問方式或方法。",
    category: "疑問詞",
    hint: "詢問方式",
  },
  {
    id: "blank-145",
    sentence: "We eat breakfast at seven o'clock.",
    blankSentence: "We eat breakfast at seven ___.",
    answer: "o'clock",
    acceptableAnswers: ["o'clock", "oclock"],
    translation: "我們七點吃早餐。",
    explanation: "o'clock 表示整點時間；可接受少打撇號的 oclock。",
    category: "時間",
    hint: "表示整點",
  },
  {
    id: "blank-146",
    sentence: "The movie starts at noon.",
    blankSentence: "The movie starts at ___.",
    answer: "noon",
    acceptableAnswers: ["noon"],
    translation: "電影在中午開始。",
    explanation: "noon 表示中午十二點。",
    category: "時間",
    hint: "中午十二點",
  },
  {
    id: "blank-147",
    sentence: "I do my homework after dinner.",
    blankSentence: "I do my homework ___ dinner.",
    answer: "after",
    acceptableAnswers: ["after"],
    translation: "我晚餐後做功課。",
    explanation: "after 表示在……之後。",
    category: "時間",
    hint: "表示在之後",
  },
  {
    id: "blank-148",
    sentence: "The school trip is in June.",
    blankSentence: "The school trip is in ___.",
    answer: "June",
    acceptableAnswers: ["June", "june"],
    translation: "校外教學在六月。",
    explanation: "June 表示六月，月份前常用 in。",
    category: "時間",
    hint: "一年中的月份",
  },
  {
    id: "blank-149",
    sentence: "She goes to Taipei by train.",
    blankSentence: "She goes to Taipei by ___.",
    answer: "train",
    acceptableAnswers: ["train"],
    translation: "她搭火車去台北。",
    explanation: "by train 表示搭火車。",
    category: "交通",
    hint: "在鐵軌上行駛",
  },
  {
    id: "blank-150",
    sentence: "My uncle rides a scooter to work.",
    blankSentence: "My uncle rides a ___ to work.",
    answer: "scooter",
    acceptableAnswers: ["scooter"],
    translation: "我叔叔騎機車去上班。",
    explanation: "scooter 表示機車或小型速克達。",
    category: "交通",
    hint: "常見兩輪交通工具",
  },
  {
    id: "blank-151",
    sentence: "We take the MRT to the zoo.",
    blankSentence: "We take the ___ to the zoo.",
    answer: "MRT",
    acceptableAnswers: ["MRT", "mrt"],
    translation: "我們搭捷運去動物園。",
    explanation: "MRT 是捷運，在城市交通中常見。",
    category: "交通",
    hint: "城市裡的捷運",
  },
  {
    id: "blank-152",
    sentence: "He walks to the store.",
    blankSentence: "He ___ to the store.",
    answer: "walks",
    acceptableAnswers: ["walks"],
    translation: "他走路去商店。",
    explanation: "主詞 He 是第三人稱單數，walk 要加 s。",
    category: "交通",
    hint: "不用車，用腳移動",
  },
  {
    id: "blank-153",
    sentence: "I brush my teeth every morning.",
    blankSentence: "I brush my ___ every morning.",
    answer: "teeth",
    acceptableAnswers: ["teeth"],
    translation: "我每天早上刷牙。",
    explanation: "brush my teeth 是刷牙的常用說法。",
    category: "日常生活",
    hint: "刷牙時清潔的部分",
  },
  {
    id: "blank-154",
    sentence: "Please put the dishes on the table.",
    blankSentence: "Please put the ___ on the table.",
    answer: "dishes",
    acceptableAnswers: ["dishes"],
    translation: "請把盤子放在桌上。",
    explanation: "dishes 可表示餐具或盤子，這裡是日常用餐物品。",
    category: "日常生活",
    hint: "吃飯會用到的物品",
  },
  {
    id: "blank-155",
    sentence: "I take a shower at night.",
    blankSentence: "I take a ___ at night.",
    answer: "shower",
    acceptableAnswers: ["shower"],
    translation: "我晚上洗澡。",
    explanation: "take a shower 表示淋浴、洗澡。",
    category: "日常生活",
    hint: "洗澡的常用名詞",
  },
  {
    id: "blank-156",
    sentence: "Mom makes breakfast for us.",
    blankSentence: "Mom makes ___ for us.",
    answer: "breakfast",
    acceptableAnswers: ["breakfast"],
    translation: "媽媽為我們做早餐。",
    explanation: "breakfast 表示早餐，是一天中的第一餐。",
    category: "日常生活",
    hint: "早上的一餐",
  },
  {
    id: "blank-157",
    sentence: "There are three apples on the plate.",
    blankSentence: "There are three ___ on the plate.",
    answer: "apples",
    acceptableAnswers: ["apples"],
    translation: "盤子上有三顆蘋果。",
    explanation: "three 後面接可數名詞複數，所以 apple 要用 apples。",
    category: "可數不可數",
    hint: "three 後用複數名詞",
  },
  {
    id: "blank-158",
    sentence: "There is some water in the bottle.",
    blankSentence: "There is some ___ in the bottle.",
    answer: "water",
    acceptableAnswers: ["water"],
    translation: "瓶子裡有一些水。",
    explanation: "water 是不可數名詞，可和 some 搭配。",
    category: "可數不可數",
    hint: "不可數的飲品",
  },
  {
    id: "blank-159",
    sentence: "I need two pencils.",
    blankSentence: "I need two ___.",
    answer: "pencils",
    acceptableAnswers: ["pencils"],
    translation: "我需要兩枝鉛筆。",
    explanation: "two 後面接可數名詞複數，pencil 要加 s。",
    category: "可數不可數",
    hint: "two 後用複數名詞",
  },
  {
    id: "blank-160",
    sentence: "There is a little rice in the bowl.",
    blankSentence: "There is a little ___ in the bowl.",
    answer: "rice",
    acceptableAnswers: ["rice"],
    translation: "碗裡有一點飯。",
    explanation: "rice 是不可數名詞，可用 a little 修飾。",
    category: "可數不可數",
    hint: "不可數的主食",
  },
  {
    id: "blank-161",
    sentence: "This is Jack. He is my cousin.",
    blankSentence: "This is Jack. ___ is my cousin.",
    answer: "He",
    acceptableAnswers: ["He", "he"],
    translation: "這是 Jack。他是我的表哥。",
    explanation: "Jack 是男生名字，主格代名詞用 He。",
    category: "代名詞",
    hint: "男生主格代名詞",
  },
  {
    id: "blank-162",
    sentence: "These are my books. They are new.",
    blankSentence: "These are my books. ___ are new.",
    answer: "They",
    acceptableAnswers: ["They", "they"],
    translation: "這些是我的書。它們是新的。",
    explanation: "books 是複數，主格代名詞用 They。",
    category: "代名詞",
    hint: "複數主格代名詞",
  },
  {
    id: "blank-163",
    sentence: "Mary and I are classmates. We study together.",
    blankSentence: "Mary and I are classmates. ___ study together.",
    answer: "We",
    acceptableAnswers: ["We", "we"],
    translation: "Mary 和我是同學。我們一起讀書。",
    explanation: "Mary and I 包含說話者自己，主格代名詞用 We。",
    category: "代名詞",
    hint: "包含自己的複數代名詞",
  },
  {
    id: "blank-164",
    sentence: "This is a cat. It is black.",
    blankSentence: "This is a cat. ___ is black.",
    answer: "It",
    acceptableAnswers: ["It", "it"],
    translation: "這是一隻貓。牠是黑色的。",
    explanation: "單數動物 cat 可用 It 代替。",
    category: "代名詞",
    hint: "代替單數動物",
  },
  {
    id: "blank-165",
    sentence: "This is Lisa's pen. It is her pen.",
    blankSentence: "This is Lisa's pen. It is ___ pen.",
    answer: "her",
    acceptableAnswers: ["her"],
    translation: "這是 Lisa 的筆。這是她的筆。",
    explanation: "Lisa 是女生，後面接名詞 pen 時用所有格 her。",
    category: "所有格",
    hint: "女生的所有格",
  },
  {
    id: "blank-166",
    sentence: "This is my parents' room. It is their room.",
    blankSentence: "This is my parents' room. It is ___ room.",
    answer: "their",
    acceptableAnswers: ["their"],
    translation: "這是我父母的房間。這是他們的房間。",
    explanation: "parents 是複數，後面接 room 時用所有格 their。",
    category: "所有格",
    hint: "複數人物的所有格",
  },
  {
    id: "blank-167",
    sentence: "That is our classroom.",
    blankSentence: "That is ___ classroom.",
    answer: "our",
    acceptableAnswers: ["our"],
    translation: "那是我們的教室。",
    explanation: "our 表示我們的，後面可接名詞 classroom。",
    category: "所有格",
    hint: "表示我們的",
  },
  {
    id: "blank-168",
    sentence: "Is this your jacket?",
    blankSentence: "Is this ___ jacket?",
    answer: "your",
    acceptableAnswers: ["your"],
    translation: "這是你的外套嗎？",
    explanation: "your 表示你的，常用於詢問對方的物品。",
    category: "所有格",
    hint: "表示你的",
  },
  {
    id: "blank-169",
    sentence: "I always wash my hands before dinner.",
    blankSentence: "I ___ wash my hands before dinner.",
    answer: "always",
    acceptableAnswers: ["always"],
    translation: "我總是在晚餐前洗手。",
    explanation: "always 表示總是，是頻率副詞。",
    category: "頻率副詞",
    hint: "表示每次都做",
  },
  {
    id: "blank-170",
    sentence: "She usually goes to bed at ten.",
    blankSentence: "She ___ goes to bed at ten.",
    answer: "usually",
    acceptableAnswers: ["usually"],
    translation: "她通常十點上床睡覺。",
    explanation: "usually 表示通常，表示常常發生但不是每次。",
    category: "頻率副詞",
    hint: "表示通常",
  },
  {
    id: "blank-171",
    sentence: "We sometimes play cards after dinner.",
    blankSentence: "We ___ play cards after dinner.",
    answer: "sometimes",
    acceptableAnswers: ["sometimes"],
    translation: "我們有時晚餐後玩牌。",
    explanation: "sometimes 表示有時候，是頻率副詞。",
    category: "頻率副詞",
    hint: "表示有時候",
  },
  {
    id: "blank-172",
    sentence: "He never eats fish.",
    blankSentence: "He ___ eats fish.",
    answer: "never",
    acceptableAnswers: ["never"],
    translation: "他從不吃魚。",
    explanation: "never 表示從不，是頻率副詞。",
    category: "頻率副詞",
    hint: "表示完全不",
  },
  {
    id: "blank-173",
    sentence: "There are many trees in the park.",
    blankSentence: "There are ___ trees in the park.",
    answer: "many",
    acceptableAnswers: ["many"],
    translation: "公園裡有很多樹。",
    explanation: "many 修飾可數名詞複數 trees。",
    category: "數量詞",
    hint: "修飾可數複數",
  },
  {
    id: "blank-174",
    sentence: "There is much milk in the bottle.",
    blankSentence: "There is ___ milk in the bottle.",
    answer: "much",
    acceptableAnswers: ["much"],
    translation: "瓶子裡有很多牛奶。",
    explanation: "much 修飾不可數名詞 milk。",
    category: "數量詞",
    hint: "修飾不可數名詞",
  },
  {
    id: "blank-175",
    sentence: "I have a few friends in this class.",
    blankSentence: "I have ___ few friends in this class.",
    answer: "a",
    acceptableAnswers: ["a"],
    translation: "我在這個班上有幾個朋友。",
    explanation: "a few 表示幾個，後面接可數複數名詞。",
    category: "數量詞",
    hint: "和 few 組成表示幾個",
  },
  {
    id: "blank-176",
    sentence: "There is a lot of rain today.",
    blankSentence: "There is ___ lot of rain today.",
    answer: "a",
    acceptableAnswers: ["a"],
    translation: "今天有很多雨。",
    explanation: "a lot of 表示很多，可修飾不可數名詞 rain。",
    category: "數量詞",
    hint: "和 lot of 組成很多",
  },
  {
    id: "blank-177",
    sentence: "I need a pen and an eraser.",
    blankSentence: "I need a pen ___ an eraser.",
    answer: "and",
    acceptableAnswers: ["and"],
    translation: "我需要一枝筆和一個橡皮擦。",
    explanation: "and 連接兩個名詞，表示兩者都需要。",
    category: "連接詞",
    hint: "表示和",
  },
  {
    id: "blank-178",
    sentence: "It is cold, so I wear a coat.",
    blankSentence: "It is cold, ___ I wear a coat.",
    answer: "so",
    acceptableAnswers: ["so"],
    translation: "天氣很冷，所以我穿外套。",
    explanation: "so 表示所以，連接原因和結果。",
    category: "連接詞",
    hint: "表示所以",
  },
  {
    id: "blank-179",
    sentence: "Do you want tea or juice?",
    blankSentence: "Do you want tea ___ juice?",
    answer: "or",
    acceptableAnswers: ["or"],
    translation: "你想要茶還是果汁？",
    explanation: "or 用於選擇，表示或者、還是。",
    category: "連接詞",
    hint: "表示選擇",
  },
  {
    id: "blank-180",
    sentence: "I can sing, but I cannot dance.",
    blankSentence: "I can sing, ___ I cannot dance.",
    answer: "but",
    acceptableAnswers: ["but"],
    translation: "我會唱歌，但是我不會跳舞。",
    explanation: "but 表示但是，連接相反或轉折的意思。",
    category: "連接詞",
    hint: "表示但是",
  },
  {
    id: "blank-181",
    sentence: "This bag is bigger than that one.",
    blankSentence: "This bag is ___ than that one.",
    answer: "bigger",
    acceptableAnswers: ["bigger"],
    translation: "這個袋子比那個大。",
    explanation: "bigger 是 big 的比較級，後面常接 than。",
    category: "比較級",
    hint: "big 的比較級",
  },
  {
    id: "blank-182",
    sentence: "My room is cleaner than my brother's room.",
    blankSentence: "My room is ___ than my brother's room.",
    answer: "cleaner",
    acceptableAnswers: ["cleaner"],
    translation: "我的房間比我哥哥的房間乾淨。",
    explanation: "cleaner 是 clean 的比較級，用來比較兩個房間。",
    category: "比較級",
    hint: "clean 的比較級",
  },
  {
    id: "blank-183",
    sentence: "This book is easier than that book.",
    blankSentence: "This book is ___ than that book.",
    answer: "easier",
    acceptableAnswers: ["easier"],
    translation: "這本書比那本書容易。",
    explanation: "easier 是 easy 的比較級，y 變 i 再加 er。",
    category: "比較級",
    hint: "easy 的比較級",
  },
  {
    id: "blank-184",
    sentence: "Today is hotter than yesterday.",
    blankSentence: "Today is ___ than yesterday.",
    answer: "hotter",
    acceptableAnswers: ["hotter"],
    translation: "今天比昨天熱。",
    explanation: "hotter 是 hot 的比較級，雙寫 t 再加 er。",
    category: "比較級",
    hint: "hot 的比較級",
  },
  {
    id: "blank-185",
    sentence: "I watched TV last night.",
    blankSentence: "I ___ TV last night.",
    answer: "watched",
    acceptableAnswers: ["watched"],
    translation: "我昨晚看電視。",
    explanation: "last night 表示過去時間，watch 的過去式是 watched。",
    category: "過去式",
    hint: "watch 的過去式",
  },
  {
    id: "blank-186",
    sentence: "She visited her grandma yesterday.",
    blankSentence: "She ___ her grandma yesterday.",
    answer: "visited",
    acceptableAnswers: ["visited"],
    translation: "她昨天拜訪奶奶。",
    explanation: "yesterday 表示過去時間，visit 的過去式是 visited。",
    category: "過去式",
    hint: "visit 的過去式",
  },
  {
    id: "blank-187",
    sentence: "We played basketball after school yesterday.",
    blankSentence: "We ___ basketball after school yesterday.",
    answer: "played",
    acceptableAnswers: ["played"],
    translation: "我們昨天放學後打籃球。",
    explanation: "yesterday 表示過去時間，play 的過去式是 played。",
    category: "過去式",
    hint: "play 的過去式",
  },
  {
    id: "blank-188",
    sentence: "He went to the library this morning.",
    blankSentence: "He ___ to the library this morning.",
    answer: "went",
    acceptableAnswers: ["went"],
    translation: "他今天早上去了圖書館。",
    explanation: "went 是 go 的過去式，用於 this morning 這個已發生的時間。",
    category: "過去式",
    hint: "go 的過去式",
  },
  {
    id: "blank-189",
    sentence: "We will visit the museum tomorrow.",
    blankSentence: "We will ___ the museum tomorrow.",
    answer: "visit",
    acceptableAnswers: ["visit"],
    translation: "我們明天將參觀博物館。",
    explanation: "will 後面接原形動詞 visit。",
    category: "未來式",
    hint: "will 後接原形",
  },
  {
    id: "blank-190",
    sentence: "I am going to buy a new notebook.",
    blankSentence: "I am going to ___ a new notebook.",
    answer: "buy",
    acceptableAnswers: ["buy"],
    translation: "我打算買一本新筆記本。",
    explanation: "be going to 後面接原形動詞 buy，表示計畫。",
    category: "未來式",
    hint: "be going to 後接原形",
  },
  {
    id: "blank-191",
    sentence: "They will have a picnic next Sunday.",
    blankSentence: "They will ___ a picnic next Sunday.",
    answer: "have",
    acceptableAnswers: ["have"],
    translation: "他們下星期日將野餐。",
    explanation: "will 後面接原形動詞 have。",
    category: "未來式",
    hint: "will 後接原形",
  },
  {
    id: "blank-192",
    sentence: "She is going to call me tonight.",
    blankSentence: "She is going to ___ me tonight.",
    answer: "call",
    acceptableAnswers: ["call"],
    translation: "她今晚打算打電話給我。",
    explanation: "is going to 後面接原形動詞 call。",
    category: "未來式",
    hint: "be going to 後接原形",
  },
  {
    id: "blank-193",
    sentence: "Please open your book.",
    blankSentence: "Please ___ your book.",
    answer: "open",
    acceptableAnswers: ["open"],
    translation: "請打開你的書。",
    explanation: "Please 加原形動詞 open，是有禮貌的命令句。",
    category: "命令句",
    hint: "把書打開",
  },
  {
    id: "blank-194",
    sentence: "Don't run in the classroom.",
    blankSentence: "Don't ___ in the classroom.",
    answer: "run",
    acceptableAnswers: ["run"],
    translation: "不要在教室裡跑。",
    explanation: "Don't 後面接原形動詞 run，表示不要做某事。",
    category: "命令句",
    hint: "不要快速移動",
  },
  {
    id: "blank-195",
    sentence: "Please be quiet in the library.",
    blankSentence: "Please ___ quiet in the library.",
    answer: "be",
    acceptableAnswers: ["be"],
    translation: "請在圖書館保持安靜。",
    explanation: "命令句中 Please 後接原形 be，表示保持某種狀態。",
    category: "命令句",
    hint: "保持某種狀態",
  },
  {
    id: "blank-196",
    sentence: "Turn left at the corner.",
    blankSentence: "___ left at the corner.",
    answer: "Turn",
    acceptableAnswers: ["Turn", "turn"],
    translation: "在轉角左轉。",
    explanation: "Turn left 是指路時常用的命令句。",
    category: "命令句",
    hint: "指示方向的動詞",
  },
  {
    id: "blank-197",
    sentence: "I get up at seven every morning.",
    blankSentence: "I get ___ at seven every morning.",
    answer: "up",
    acceptableAnswers: ["up"],
    translation: "我每天早上七點起床。",
    explanation: "get up 是起床的常用片語。",
    category: "常用片語",
    hint: "和 get 組成起床",
  },
  {
    id: "blank-198",
    sentence: "Please take off your shoes.",
    blankSentence: "Please take ___ your shoes.",
    answer: "off",
    acceptableAnswers: ["off"],
    translation: "請脫掉你的鞋子。",
    explanation: "take off 表示脫下，常用於衣物或鞋子。",
    category: "常用片語",
    hint: "和 take 組成脫下",
  },
  {
    id: "blank-199",
    sentence: "We look for the lost dog.",
    blankSentence: "We look ___ the lost dog.",
    answer: "for",
    acceptableAnswers: ["for"],
    translation: "我們尋找走失的狗。",
    explanation: "look for 表示尋找。",
    category: "常用片語",
    hint: "和 look 組成尋找",
  },
  {
    id: "blank-200",
    sentence: "Please write down your name.",
    blankSentence: "Please write ___ your name.",
    answer: "down",
    acceptableAnswers: ["down"],
    translation: "請寫下你的名字。",
    explanation: "write down 表示寫下、記下。",
    category: "常用片語",
    hint: "和 write 組成寫下",
  },
];

window.fillBlankQuestions = fillBlankQuestions;
