const fillBlankQuestions = [
  {
    id: "blank-001",
    sentence: "I drink milk every morning.",
    blankSentence: "I drink ___ every morning.",
    answer: "milk",
    acceptableAnswers: ["milk"],
    translation: "我每天早上喝牛奶。",
    explanation: "milk 是初級常見單字，表示牛奶。",
    category: "單字",
    hint: "一種白色飲品",
  },
  {
    id: "blank-002",
    sentence: "She has a small dog.",
    blankSentence: "She has a small ___.",
    answer: "dog",
    acceptableAnswers: ["dog"],
    translation: "她有一隻小狗。",
    explanation: "dog 是常見動物單字，表示狗。",
    category: "單字",
    hint: "會汪汪叫的動物",
  },
  {
    id: "blank-003",
    sentence: "This is my book.",
    blankSentence: "This is my ___.",
    answer: "book",
    acceptableAnswers: ["book"],
    translation: "這是我的書。",
    explanation: "book 表示書，是學校與日常生活常用單字。",
    category: "單字",
    hint: "可以閱讀的東西",
  },
  {
    id: "blank-004",
    sentence: "We eat rice for lunch.",
    blankSentence: "We eat ___ for lunch.",
    answer: "rice",
    acceptableAnswers: ["rice"],
    translation: "我們午餐吃飯。",
    explanation: "rice 表示米飯，是食物類常見單字。",
    category: "單字",
    hint: "常見主食",
  },
  {
    id: "blank-005",
    sentence: "The sky is blue.",
    blankSentence: "The sky is ___.",
    answer: "blue",
    acceptableAnswers: ["blue"],
    translation: "天空是藍色的。",
    explanation: "blue 表示藍色，是基礎顏色單字。",
    category: "單字",
    hint: "天空常見的顏色",
  },
  {
    id: "blank-006",
    sentence: "They play soccer after school.",
    blankSentence: "They ___ soccer after school.",
    answer: "play",
    acceptableAnswers: ["play"],
    translation: "他們放學後踢足球。",
    explanation: "play 可搭配球類運動，例如 play soccer。",
    category: "動詞",
    hint: "做球類運動常用的動詞",
  },
  {
    id: "blank-007",
    sentence: "I read a book at night.",
    blankSentence: "I ___ a book at night.",
    answer: "read",
    acceptableAnswers: ["read"],
    translation: "我晚上讀一本書。",
    explanation: "read 表示閱讀，read a book 是常見用法。",
    category: "動詞",
    hint: "看書時做的動作",
  },
  {
    id: "blank-008",
    sentence: "We eat breakfast at seven.",
    blankSentence: "We ___ breakfast at seven.",
    answer: "eat",
    acceptableAnswers: ["eat", "have"],
    translation: "我們七點吃早餐。",
    explanation: "eat breakfast 表示吃早餐；have breakfast 也常用來表示吃早餐。",
    category: "動詞",
    hint: "吃東西的動作",
  },
  {
    id: "blank-009",
    sentence: "He likes English.",
    blankSentence: "He ___ English.",
    answer: "likes",
    acceptableAnswers: ["likes"],
    translation: "他喜歡英文。",
    explanation: "主詞 He 是第三人稱單數，現在式動詞 like 要加 s，變成 likes。",
    category: "動詞",
    hint: "like 的第三人稱單數現在式",
  },
  {
    id: "blank-010",
    sentence: "My mother cooks dinner.",
    blankSentence: "My mother ___ dinner.",
    answer: "cooks",
    acceptableAnswers: ["cooks"],
    translation: "我媽媽煮晚餐。",
    explanation: "主詞 My mother 是第三人稱單數，現在式動詞 cook 要加 s。",
    category: "動詞",
    hint: "cook 的第三人稱單數現在式",
  },
  {
    id: "blank-011",
    sentence: "She is a student.",
    blankSentence: "She ___ a student.",
    answer: "is",
    acceptableAnswers: ["is"],
    translation: "她是一名學生。",
    explanation: "主詞 She 搭配 be 動詞 is。",
    category: "be 動詞",
    hint: "She 搭配的 be 動詞",
  },
  {
    id: "blank-012",
    sentence: "I am happy.",
    blankSentence: "I ___ happy.",
    answer: "am",
    acceptableAnswers: ["am"],
    translation: "我很開心。",
    explanation: "主詞 I 搭配 be 動詞 am。",
    category: "be 動詞",
    hint: "I 搭配的 be 動詞",
  },
  {
    id: "blank-013",
    sentence: "They are friends.",
    blankSentence: "They ___ friends.",
    answer: "are",
    acceptableAnswers: ["are"],
    translation: "他們是朋友。",
    explanation: "主詞 They 是複數，搭配 be 動詞 are。",
    category: "be 動詞",
    hint: "They 搭配的 be 動詞",
  },
  {
    id: "blank-014",
    sentence: "It is sunny today.",
    blankSentence: "It ___ sunny today.",
    answer: "is",
    acceptableAnswers: ["is"],
    translation: "今天是晴天。",
    explanation: "描述天氣時常用 It is，加上天氣形容詞。",
    category: "be 動詞",
    hint: "It 搭配的 be 動詞",
  },
  {
    id: "blank-015",
    sentence: "You are my teacher.",
    blankSentence: "You ___ my teacher.",
    answer: "are",
    acceptableAnswers: ["are"],
    translation: "你是我的老師。",
    explanation: "主詞 You 搭配 be 動詞 are。",
    category: "be 動詞",
    hint: "You 搭配的 be 動詞",
  },
  {
    id: "blank-016",
    sentence: "The book is on the desk.",
    blankSentence: "The book is ___ the desk.",
    answer: "on",
    acceptableAnswers: ["on"],
    translation: "書在桌子上。",
    explanation: "on 表示在物體表面上。",
    category: "介系詞",
    hint: "表示在上面",
  },
  {
    id: "blank-017",
    sentence: "The cat is under the chair.",
    blankSentence: "The cat is ___ the chair.",
    answer: "under",
    acceptableAnswers: ["under"],
    translation: "貓在椅子下面。",
    explanation: "under 表示在某物下面。",
    category: "介系詞",
    hint: "表示在下面",
  },
  {
    id: "blank-018",
    sentence: "I live in Taipei.",
    blankSentence: "I live ___ Taipei.",
    answer: "in",
    acceptableAnswers: ["in"],
    translation: "我住在台北。",
    explanation: "live in 加上城市或地點，表示住在某地。",
    category: "介系詞",
    hint: "表示在某城市裡",
  },
  {
    id: "blank-019",
    sentence: "She goes to school.",
    blankSentence: "She goes ___ school.",
    answer: "to",
    acceptableAnswers: ["to"],
    translation: "她去學校。",
    explanation: "go to school 表示去上學或去學校。",
    category: "介系詞",
    hint: "go 後面常接的方向介系詞",
  },
  {
    id: "blank-020",
    sentence: "The store is near my house.",
    blankSentence: "The store is ___ my house.",
    answer: "near",
    acceptableAnswers: ["near"],
    translation: "那家商店在我家附近。",
    explanation: "near 表示在附近、靠近。",
    category: "介系詞",
    hint: "表示靠近",
  },
  {
    id: "blank-021",
    sentence: "What is your name?",
    blankSentence: "___ is your name?",
    answer: "What",
    acceptableAnswers: ["what", "What"],
    translation: "你的名字是什麼？",
    explanation: "What 用來詢問事物、名字或內容。",
    category: "疑問詞",
    hint: "詢問什麼",
  },
  {
    id: "blank-022",
    sentence: "Where do you live?",
    blankSentence: "___ do you live?",
    answer: "Where",
    acceptableAnswers: ["where", "Where"],
    translation: "你住在哪裡？",
    explanation: "Where 用來詢問地點。",
    category: "疑問詞",
    hint: "詢問地點",
  },
  {
    id: "blank-023",
    sentence: "Who is that boy?",
    blankSentence: "___ is that boy?",
    answer: "Who",
    acceptableAnswers: ["who", "Who"],
    translation: "那個男孩是誰？",
    explanation: "Who 用來詢問人物。",
    category: "疑問詞",
    hint: "詢問人物",
  },
  {
    id: "blank-024",
    sentence: "When is your birthday?",
    blankSentence: "___ is your birthday?",
    answer: "When",
    acceptableAnswers: ["when", "When"],
    translation: "你的生日是什麼時候？",
    explanation: "When 用來詢問時間。",
    category: "疑問詞",
    hint: "詢問時間",
  },
  {
    id: "blank-025",
    sentence: "How are you?",
    blankSentence: "___ are you?",
    answer: "How",
    acceptableAnswers: ["how", "How"],
    translation: "你好嗎？",
    explanation: "How are you? 是常見問候語。",
    category: "疑問詞",
    hint: "問候近況時使用",
  },
  {
    id: "blank-026",
    sentence: "I eat breakfast in the morning.",
    blankSentence: "I eat breakfast in the ___.",
    answer: "morning",
    acceptableAnswers: ["morning"],
    translation: "我在早上吃早餐。",
    explanation: "in the morning 表示在早上。",
    category: "時間",
    hint: "一天的開始時段",
  },
  {
    id: "blank-027",
    sentence: "We have lunch at noon.",
    blankSentence: "We have lunch at ___.",
    answer: "noon",
    acceptableAnswers: ["noon"],
    translation: "我們中午吃午餐。",
    explanation: "at noon 表示在中午。",
    category: "時間",
    hint: "中午十二點左右",
  },
  {
    id: "blank-028",
    sentence: "I go to bed at night.",
    blankSentence: "I go to bed at ___.",
    answer: "night",
    acceptableAnswers: ["night"],
    translation: "我晚上上床睡覺。",
    explanation: "at night 表示在晚上。",
    category: "時間",
    hint: "一天中天黑後的時間",
  },
  {
    id: "blank-029",
    sentence: "Today is Monday.",
    blankSentence: "Today is ___.",
    answer: "Monday",
    acceptableAnswers: ["monday", "Monday"],
    translation: "今天是星期一。",
    explanation: "Monday 表示星期一，星期名稱首字母通常大寫。",
    category: "時間",
    hint: "一週的第一個上課日",
  },
  {
    id: "blank-030",
    sentence: "My class starts at eight.",
    blankSentence: "My class starts at ___.",
    answer: "eight",
    acceptableAnswers: ["eight", "8"],
    translation: "我的課八點開始。",
    explanation: "eight 表示數字 8；時間也可簡寫成 8。",
    category: "時間",
    hint: "數字 8 的英文",
  },
  {
    id: "blank-031",
    sentence: "I go to school by bus.",
    blankSentence: "I go to school by ___.",
    answer: "bus",
    acceptableAnswers: ["bus"],
    translation: "我搭公車去上學。",
    explanation: "by bus 表示搭公車，是常見交通工具用法。",
    category: "交通",
    hint: "交通工具",
  },
  {
    id: "blank-032",
    sentence: "Tom rides a bike to the park.",
    blankSentence: "Tom rides a ___ to the park.",
    answer: "bike",
    acceptableAnswers: ["bike", "bicycle"],
    translation: "Tom 騎腳踏車去公園。",
    explanation: "bike 和 bicycle 都可以表示腳踏車。",
    category: "交通",
    hint: "兩輪交通工具",
  },
  {
    id: "blank-033",
    sentence: "My father drives a car.",
    blankSentence: "My father drives a ___.",
    answer: "car",
    acceptableAnswers: ["car"],
    translation: "我爸爸開車。",
    explanation: "drive a car 表示開車。",
    category: "交通",
    hint: "常見四輪交通工具",
  },
  {
    id: "blank-034",
    sentence: "We take the train to Tainan.",
    blankSentence: "We take the ___ to Tainan.",
    answer: "train",
    acceptableAnswers: ["train"],
    translation: "我們搭火車去台南。",
    explanation: "take the train 表示搭火車。",
    category: "交通",
    hint: "在鐵軌上行駛的交通工具",
  },
  {
    id: "blank-035",
    sentence: "The bus stop is near the school.",
    blankSentence: "The ___ stop is near the school.",
    answer: "bus",
    acceptableAnswers: ["bus"],
    translation: "公車站在學校附近。",
    explanation: "bus stop 表示公車站。",
    category: "交通",
    hint: "bus stop 的第一個字",
  },
  {
    id: "blank-036",
    sentence: "I brush my teeth every day.",
    blankSentence: "I brush my ___ every day.",
    answer: "teeth",
    acceptableAnswers: ["teeth"],
    translation: "我每天刷牙。",
    explanation: "brush my teeth 表示刷牙，teeth 是 tooth 的複數。",
    category: "日常生活",
    hint: "刷牙時清潔的部位",
  },
  {
    id: "blank-037",
    sentence: "She washes her hands before dinner.",
    blankSentence: "She washes her ___ before dinner.",
    answer: "hands",
    acceptableAnswers: ["hands"],
    translation: "她晚餐前洗手。",
    explanation: "wash hands 表示洗手，是日常生活常用語。",
    category: "日常生活",
    hint: "吃飯前常清洗的身體部位",
  },
  {
    id: "blank-038",
    sentence: "We watch TV after dinner.",
    blankSentence: "We watch ___ after dinner.",
    answer: "TV",
    acceptableAnswers: ["tv", "TV", "television"],
    translation: "我們晚餐後看電視。",
    explanation: "watch TV 表示看電視；TV 也可以寫成 television。",
    category: "日常生活",
    hint: "晚餐後常看的家電或節目",
  },
  {
    id: "blank-039",
    sentence: "I do my homework after school.",
    blankSentence: "I do my ___ after school.",
    answer: "homework",
    acceptableAnswers: ["homework"],
    translation: "我放學後做作業。",
    explanation: "do my homework 表示做我的作業。",
    category: "日常生活",
    hint: "學生放學後要完成的功課",
  },
  {
    id: "blank-040",
    sentence: "He cleans his room on Saturday.",
    blankSentence: "He cleans his ___ on Saturday.",
    answer: "room",
    acceptableAnswers: ["room"],
    translation: "他星期六打掃他的房間。",
    explanation: "clean one's room 表示打掃某人的房間。",
    category: "日常生活",
    hint: "睡覺或讀書的房間",
  },
  {
    id: "blank-041",
    sentence: "I eat an apple after lunch.",
    blankSentence: "I eat an ___ after lunch.",
    answer: "apple",
    acceptableAnswers: ["apple"],
    translation: "我午餐後吃一顆蘋果。",
    explanation: "apple 是常見水果單字，母音開頭前可用 an。",
    category: "單字",
    hint: "一種常見水果",
  },
  {
    id: "blank-042",
    sentence: "She reads a story after dinner.",
    blankSentence: "She reads a ___ after dinner.",
    answer: "story",
    acceptableAnswers: ["story"],
    translation: "她晚餐後讀一個故事。",
    explanation: "story 表示故事，是初級常見閱讀相關單字。",
    category: "單字",
    hint: "可以被閱讀的短篇內容",
  },
  {
    id: "blank-043",
    sentence: "My brother has a pencil.",
    blankSentence: "My brother has a ___.",
    answer: "pencil",
    acceptableAnswers: ["pencil"],
    translation: "我哥哥有一枝鉛筆。",
    explanation: "pencil 表示鉛筆，是常見文具單字。",
    category: "單字",
    hint: "寫字用的文具",
  },
  {
    id: "blank-044",
    sentence: "We see many birds in the tree.",
    blankSentence: "We see many ___ in the tree.",
    answer: "birds",
    acceptableAnswers: ["birds"],
    translation: "我們看到樹上有許多鳥。",
    explanation: "birds 是 bird 的複數，表示許多鳥。",
    category: "單字",
    hint: "會飛的動物複數",
  },
  {
    id: "blank-045",
    sentence: "The baby drinks water.",
    blankSentence: "The baby drinks ___.",
    answer: "water",
    acceptableAnswers: ["water"],
    translation: "那個嬰兒喝水。",
    explanation: "water 表示水，是不可數名詞。",
    category: "單字",
    hint: "透明的飲品",
  },
  {
    id: "blank-046",
    sentence: "I study English every day.",
    blankSentence: "I ___ English every day.",
    answer: "study",
    acceptableAnswers: ["study"],
    translation: "我每天讀英文。",
    explanation: "study 表示讀書、學習，study English 是常見用法。",
    category: "動詞",
    hint: "學習功課的動作",
  },
  {
    id: "blank-047",
    sentence: "They walk to school.",
    blankSentence: "They ___ to school.",
    answer: "walk",
    acceptableAnswers: ["walk"],
    translation: "他們走路去學校。",
    explanation: "walk 表示走路，主詞 They 用原形動詞。",
    category: "動詞",
    hint: "不用交通工具時的移動方式",
  },
  {
    id: "blank-048",
    sentence: "We listen to music at night.",
    blankSentence: "We ___ to music at night.",
    answer: "listen",
    acceptableAnswers: ["listen"],
    translation: "我們晚上聽音樂。",
    explanation: "listen to music 表示聽音樂，listen 後常接 to。",
    category: "動詞",
    hint: "用耳朵聽的動作",
  },
  {
    id: "blank-049",
    sentence: "He watches TV on Sunday.",
    blankSentence: "He ___ TV on Sunday.",
    answer: "watches",
    acceptableAnswers: ["watches"],
    translation: "他星期日看電視。",
    explanation: "主詞 He 是第三人稱單數，watch 要加 es 變成 watches。",
    category: "動詞",
    hint: "watch 的第三人稱單數現在式",
  },
  {
    id: "blank-050",
    sentence: "Mary sings a song in class.",
    blankSentence: "Mary ___ a song in class.",
    answer: "sings",
    acceptableAnswers: ["sings"],
    translation: "Mary 在課堂上唱一首歌。",
    explanation: "主詞 Mary 是第三人稱單數，sing 要加 s。",
    category: "動詞",
    hint: "sing 的第三人稱單數現在式",
  },
  {
    id: "blank-051",
    sentence: "My parents are busy today.",
    blankSentence: "My parents ___ busy today.",
    answer: "are",
    acceptableAnswers: ["are"],
    translation: "我父母今天很忙。",
    explanation: "My parents 是複數主詞，be 動詞要用 are。",
    category: "be 動詞",
    hint: "複數主詞常用的 be 動詞",
  },
  {
    id: "blank-052",
    sentence: "This bag is heavy.",
    blankSentence: "This bag ___ heavy.",
    answer: "is",
    acceptableAnswers: ["is"],
    translation: "這個袋子很重。",
    explanation: "This bag 是單數主詞，現在式 be 動詞用 is。",
    category: "be 動詞",
    hint: "單數物品常用的 be 動詞",
  },
  {
    id: "blank-053",
    sentence: "We are classmates.",
    blankSentence: "We ___ classmates.",
    answer: "are",
    acceptableAnswers: ["are"],
    translation: "我們是同班同學。",
    explanation: "主詞 We 搭配 be 動詞 are。",
    category: "be 動詞",
    hint: "We 搭配的 be 動詞",
  },
  {
    id: "blank-054",
    sentence: "The flowers are beautiful.",
    blankSentence: "The flowers ___ beautiful.",
    answer: "are",
    acceptableAnswers: ["are"],
    translation: "這些花很漂亮。",
    explanation: "The flowers 是複數主詞，be 動詞用 are。",
    category: "be 動詞",
    hint: "複數名詞搭配的 be 動詞",
  },
  {
    id: "blank-055",
    sentence: "It is cold in winter.",
    blankSentence: "It ___ cold in winter.",
    answer: "is",
    acceptableAnswers: ["is"],
    translation: "冬天天氣很冷。",
    explanation: "描述天氣或季節狀況時常用 It is。",
    category: "be 動詞",
    hint: "It 搭配的 be 動詞",
  },
  {
    id: "blank-056",
    sentence: "I can ride a bike.",
    blankSentence: "I ___ ride a bike.",
    answer: "can",
    acceptableAnswers: ["can"],
    translation: "我會騎腳踏車。",
    explanation: "can 表示會、能夠，後面接原形動詞。",
    category: "助動詞",
    hint: "表示能力的助動詞",
  },
  {
    id: "blank-057",
    sentence: "You must not run here.",
    blankSentence: "You ___ not run here.",
    answer: "must",
    acceptableAnswers: ["must"],
    translation: "你不可以在這裡跑。",
    explanation: "must not 表示禁止或不可以。",
    category: "助動詞",
    hint: "表示規定或禁止的助動詞",
  },
  {
    id: "blank-058",
    sentence: "May I use your pen?",
    blankSentence: "___ I use your pen?",
    answer: "May",
    acceptableAnswers: ["may", "May"],
    translation: "我可以用你的筆嗎？",
    explanation: "May I...? 是禮貌地請求允許的句型。",
    category: "助動詞",
    hint: "禮貌請求允許時常用",
  },
  {
    id: "blank-059",
    sentence: "He cannot swim.",
    blankSentence: "He ___ swim.",
    answer: "cannot",
    acceptableAnswers: ["cannot", "can't", "cant"],
    translation: "他不會游泳。",
    explanation: "cannot 和 can't 都表示不能或不會。",
    category: "助動詞",
    hint: "can 的否定形式",
  },
  {
    id: "blank-060",
    sentence: "We should clean our classroom.",
    blankSentence: "We ___ clean our classroom.",
    answer: "should",
    acceptableAnswers: ["should"],
    translation: "我們應該打掃教室。",
    explanation: "should 表示應該，後面接原形動詞。",
    category: "助動詞",
    hint: "表示應該的助動詞",
  },
  {
    id: "blank-061",
    sentence: "The ball is in the box.",
    blankSentence: "The ball is ___ the box.",
    answer: "in",
    acceptableAnswers: ["in"],
    translation: "球在盒子裡。",
    explanation: "in 表示在某物裡面。",
    category: "介系詞",
    hint: "表示在裡面",
  },
  {
    id: "blank-062",
    sentence: "I go to school by bus.",
    blankSentence: "I go to school ___ bus.",
    answer: "by",
    acceptableAnswers: ["by"],
    translation: "我搭公車去上學。",
    explanation: "by bus 表示搭公車，交通工具前常用 by。",
    category: "介系詞",
    hint: "交通工具前常用的介系詞",
  },
  {
    id: "blank-063",
    sentence: "She sits next to me.",
    blankSentence: "She sits next ___ me.",
    answer: "to",
    acceptableAnswers: ["to"],
    translation: "她坐在我旁邊。",
    explanation: "next to 表示在旁邊，是常見位置用法。",
    category: "介系詞",
    hint: "next 後面的介系詞",
  },
  {
    id: "blank-064",
    sentence: "The library is across from the park.",
    blankSentence: "The library is across ___ the park.",
    answer: "from",
    acceptableAnswers: ["from"],
    translation: "圖書館在公園對面。",
    explanation: "across from 表示在對面。",
    category: "介系詞",
    hint: "across 後面常接的介系詞",
  },
  {
    id: "blank-065",
    sentence: "We meet at the station.",
    blankSentence: "We meet ___ the station.",
    answer: "at",
    acceptableAnswers: ["at"],
    translation: "我們在車站見面。",
    explanation: "at 可表示在某個明確地點。",
    category: "介系詞",
    hint: "表示在某個地點",
  },
  {
    id: "blank-066",
    sentence: "Why are you late?",
    blankSentence: "___ are you late?",
    answer: "Why",
    acceptableAnswers: ["why", "Why"],
    translation: "你為什麼遲到？",
    explanation: "Why 用來詢問原因。",
    category: "疑問詞",
    hint: "詢問原因的疑問詞",
  },
  {
    id: "blank-067",
    sentence: "Which color do you like?",
    blankSentence: "___ color do you like?",
    answer: "Which",
    acceptableAnswers: ["which", "Which"],
    translation: "你喜歡哪一個顏色？",
    explanation: "Which 用來詢問哪一個。",
    category: "疑問詞",
    hint: "詢問哪一個",
  },
  {
    id: "blank-068",
    sentence: "What time is it?",
    blankSentence: "___ time is it?",
    answer: "What",
    acceptableAnswers: ["what", "What"],
    translation: "現在幾點？",
    explanation: "What time is it? 是詢問時間的常用句型。",
    category: "疑問詞",
    hint: "問時間時常用的疑問詞",
  },
  {
    id: "blank-069",
    sentence: "How old are you?",
    blankSentence: "How ___ are you?",
    answer: "old",
    acceptableAnswers: ["old"],
    translation: "你幾歲？",
    explanation: "How old 用來詢問年齡。",
    category: "疑問詞",
    hint: "詢問年齡時接在 How 後面",
  },
  {
    id: "blank-070",
    sentence: "Who is your English teacher?",
    blankSentence: "___ is your English teacher?",
    answer: "Who",
    acceptableAnswers: ["who", "Who"],
    translation: "誰是你的英文老師？",
    explanation: "Who 用來詢問人物。",
    category: "疑問詞",
    hint: "詢問人物的疑問詞",
  },
  {
    id: "blank-071",
    sentence: "We go home at five o'clock.",
    blankSentence: "We go home at five ___.",
    answer: "o'clock",
    acceptableAnswers: ["o'clock", "oclock"],
    translation: "我們五點回家。",
    explanation: "o'clock 用在整點時間後面，也可寫成 oclock 方便輸入。",
    category: "時間",
    hint: "整點時間常用字",
  },
  {
    id: "blank-072",
    sentence: "School starts in September.",
    blankSentence: "School starts in ___.",
    answer: "September",
    acceptableAnswers: ["september", "September"],
    translation: "學校九月開學。",
    explanation: "September 表示九月，月份名稱首字母通常大寫。",
    category: "時間",
    hint: "一年中的第九個月",
  },
  {
    id: "blank-073",
    sentence: "I play basketball on Friday.",
    blankSentence: "I play basketball on ___.",
    answer: "Friday",
    acceptableAnswers: ["friday", "Friday"],
    translation: "我星期五打籃球。",
    explanation: "Friday 表示星期五，星期名稱首字母通常大寫。",
    category: "時間",
    hint: "星期五的英文",
  },
  {
    id: "blank-074",
    sentence: "We have dinner at six thirty.",
    blankSentence: "We have dinner at six ___.",
    answer: "thirty",
    acceptableAnswers: ["thirty", "30"],
    translation: "我們六點三十分吃晚餐。",
    explanation: "six thirty 表示六點三十分，也可用 30 表示分鐘。",
    category: "時間",
    hint: "表示三十分的英文",
  },
  {
    id: "blank-075",
    sentence: "My birthday is in May.",
    blankSentence: "My birthday is in ___.",
    answer: "May",
    acceptableAnswers: ["may", "May"],
    translation: "我的生日在五月。",
    explanation: "May 表示五月，月份名稱首字母通常大寫。",
    category: "時間",
    hint: "一年中的第五個月",
  },
  {
    id: "blank-076",
    sentence: "She takes the MRT to Taipei.",
    blankSentence: "She takes the ___ to Taipei.",
    answer: "MRT",
    acceptableAnswers: ["mrt", "MRT"],
    translation: "她搭捷運去台北。",
    explanation: "MRT 表示捷運，是台灣常見交通工具。",
    category: "交通",
    hint: "城市中常見的捷運系統",
  },
  {
    id: "blank-077",
    sentence: "I walk to the store.",
    blankSentence: "I ___ to the store.",
    answer: "walk",
    acceptableAnswers: ["walk"],
    translation: "我走路去商店。",
    explanation: "walk 表示走路，也可用在交通方式。",
    category: "交通",
    hint: "不用車時的移動方式",
  },
  {
    id: "blank-078",
    sentence: "The taxi is yellow.",
    blankSentence: "The ___ is yellow.",
    answer: "taxi",
    acceptableAnswers: ["taxi", "cab"],
    translation: "那輛計程車是黃色的。",
    explanation: "taxi 表示計程車；cab 也可表示計程車。",
    category: "交通",
    hint: "可以付費搭乘的車",
  },
  {
    id: "blank-079",
    sentence: "We wait for the bus.",
    blankSentence: "We wait for the ___.",
    answer: "bus",
    acceptableAnswers: ["bus"],
    translation: "我們等公車。",
    explanation: "wait for the bus 表示等公車。",
    category: "交通",
    hint: "在公車站等的交通工具",
  },
  {
    id: "blank-080",
    sentence: "He rides a scooter to work.",
    blankSentence: "He rides a ___ to work.",
    answer: "scooter",
    acceptableAnswers: ["scooter"],
    translation: "他騎機車去上班。",
    explanation: "scooter 表示機車或速克達，是常見交通單字。",
    category: "交通",
    hint: "台灣常見的兩輪機動車",
  },
  {
    id: "blank-081",
    sentence: "I take a shower every night.",
    blankSentence: "I take a ___ every night.",
    answer: "shower",
    acceptableAnswers: ["shower"],
    translation: "我每天晚上洗澡。",
    explanation: "take a shower 表示淋浴、洗澡。",
    category: "日常生活",
    hint: "晚上常做的清潔活動",
  },
  {
    id: "blank-082",
    sentence: "She makes her bed every morning.",
    blankSentence: "She makes her ___ every morning.",
    answer: "bed",
    acceptableAnswers: ["bed"],
    translation: "她每天早上整理床鋪。",
    explanation: "make one's bed 表示整理床鋪。",
    category: "日常生活",
    hint: "睡覺用的家具",
  },
  {
    id: "blank-083",
    sentence: "We eat dinner with our family.",
    blankSentence: "We eat ___ with our family.",
    answer: "dinner",
    acceptableAnswers: ["dinner"],
    translation: "我們和家人一起吃晚餐。",
    explanation: "dinner 表示晚餐，是日常三餐之一。",
    category: "日常生活",
    hint: "晚上的一餐",
  },
  {
    id: "blank-084",
    sentence: "I put on my shoes.",
    blankSentence: "I put on my ___.",
    answer: "shoes",
    acceptableAnswers: ["shoes"],
    translation: "我穿上我的鞋子。",
    explanation: "put on shoes 表示穿上鞋子，shoes 通常用複數。",
    category: "日常生活",
    hint: "穿在腳上的物品",
  },
  {
    id: "blank-085",
    sentence: "He opens the door.",
    blankSentence: "He opens the ___.",
    answer: "door",
    acceptableAnswers: ["door"],
    translation: "他打開門。",
    explanation: "door 表示門，是家中常見物品。",
    category: "日常生活",
    hint: "進出房間會打開的東西",
  },
  {
    id: "blank-086",
    sentence: "I need some sugar.",
    blankSentence: "I need some ___.",
    answer: "sugar",
    acceptableAnswers: ["sugar"],
    translation: "我需要一些糖。",
    explanation: "sugar 表示糖，作為食材時常當不可數名詞。",
    category: "可數不可數",
    hint: "甜的調味品",
  },
  {
    id: "blank-087",
    sentence: "There are three apples on the table.",
    blankSentence: "There are three ___ on the table.",
    answer: "apples",
    acceptableAnswers: ["apples"],
    translation: "桌上有三顆蘋果。",
    explanation: "three 後面接可數名詞複數，所以 apple 要加 s。",
    category: "可數不可數",
    hint: "apple 的複數",
  },
  {
    id: "blank-088",
    sentence: "She has two brothers.",
    blankSentence: "She has two ___.",
    answer: "brothers",
    acceptableAnswers: ["brothers"],
    translation: "她有兩個兄弟。",
    explanation: "two 後面接可數名詞複數，brother 要加 s。",
    category: "可數不可數",
    hint: "brother 的複數",
  },
  {
    id: "blank-089",
    sentence: "I drink a glass of milk.",
    blankSentence: "I drink a glass of ___.",
    answer: "milk",
    acceptableAnswers: ["milk"],
    translation: "我喝一杯牛奶。",
    explanation: "milk 是不可數名詞，可用 a glass of 表示一杯。",
    category: "可數不可數",
    hint: "可用杯子裝的白色飲品",
  },
  {
    id: "blank-090",
    sentence: "There is some bread on the plate.",
    blankSentence: "There is some ___ on the plate.",
    answer: "bread",
    acceptableAnswers: ["bread"],
    translation: "盤子上有一些麵包。",
    explanation: "bread 常作不可數名詞，前面可用 some。",
    category: "可數不可數",
    hint: "常見早餐食物",
  },
  {
    id: "blank-091",
    sentence: "Tom is my brother. He is ten years old.",
    blankSentence: "Tom is my brother. ___ is ten years old.",
    answer: "He",
    acceptableAnswers: ["he", "He"],
    translation: "Tom 是我的哥哥。他十歲。",
    explanation: "Tom 是男生，作主詞時可用代名詞 He。",
    category: "代名詞",
    hint: "男生作主詞時常用",
  },
  {
    id: "blank-092",
    sentence: "Mary is my sister. I like her.",
    blankSentence: "Mary is my sister. I like ___.",
    answer: "her",
    acceptableAnswers: ["her"],
    translation: "Mary 是我的姊妹。我喜歡她。",
    explanation: "Mary 是女生，作受詞時可用 her。",
    category: "代名詞",
    hint: "女生作受詞時常用",
  },
  {
    id: "blank-093",
    sentence: "My dog is cute. It is small.",
    blankSentence: "My dog is cute. ___ is small.",
    answer: "It",
    acceptableAnswers: ["it", "It"],
    translation: "我的狗很可愛。牠很小。",
    explanation: "動物或事物作主詞時常可用 It。",
    category: "代名詞",
    hint: "動物或事物作主詞時常用",
  },
  {
    id: "blank-094",
    sentence: "Jack and I are classmates. We study together.",
    blankSentence: "Jack and I are classmates. ___ study together.",
    answer: "We",
    acceptableAnswers: ["we", "We"],
    translation: "Jack 和我是同班同學。我們一起讀書。",
    explanation: "Jack and I 表示我們，作主詞時用 We。",
    category: "代名詞",
    hint: "包含自己和別人時常用",
  },
  {
    id: "blank-095",
    sentence: "The students are here. They are quiet.",
    blankSentence: "The students are here. ___ are quiet.",
    answer: "They",
    acceptableAnswers: ["they", "They"],
    translation: "學生們在這裡。他們很安靜。",
    explanation: "複數的人或物作主詞時可用 They。",
    category: "代名詞",
    hint: "複數主詞常用",
  },
  {
    id: "blank-096",
    sentence: "This is my pencil.",
    blankSentence: "This is ___ pencil.",
    answer: "my",
    acceptableAnswers: ["my"],
    translation: "這是我的鉛筆。",
    explanation: "my 表示我的，後面接名詞。",
    category: "所有格",
    hint: "表示我的",
  },
  {
    id: "blank-097",
    sentence: "That is his bike.",
    blankSentence: "That is ___ bike.",
    answer: "his",
    acceptableAnswers: ["his"],
    translation: "那是他的腳踏車。",
    explanation: "his 表示他的，後面可接名詞。",
    category: "所有格",
    hint: "表示他的",
  },
  {
    id: "blank-098",
    sentence: "This is her bag.",
    blankSentence: "This is ___ bag.",
    answer: "her",
    acceptableAnswers: ["her"],
    translation: "這是她的袋子。",
    explanation: "her 表示她的，後面接名詞。",
    category: "所有格",
    hint: "表示她的",
  },
  {
    id: "blank-099",
    sentence: "Our school is big.",
    blankSentence: "___ school is big.",
    answer: "Our",
    acceptableAnswers: ["our", "Our"],
    translation: "我們的學校很大。",
    explanation: "Our 表示我們的，放在名詞 school 前面。",
    category: "所有格",
    hint: "表示我們的",
  },
  {
    id: "blank-100",
    sentence: "Their house is near the park.",
    blankSentence: "___ house is near the park.",
    answer: "Their",
    acceptableAnswers: ["their", "Their"],
    translation: "他們的房子在公園附近。",
    explanation: "Their 表示他們的，後面接名詞。",
    category: "所有格",
    hint: "表示他們的",
  },
  {
    id: "blank-101",
    sentence: "I usually eat breakfast at seven.",
    blankSentence: "I ___ eat breakfast at seven.",
    answer: "usually",
    acceptableAnswers: ["usually"],
    translation: "我通常七點吃早餐。",
    explanation: "usually 表示通常，是頻率副詞。",
    category: "頻率副詞",
    hint: "表示通常",
  },
  {
    id: "blank-102",
    sentence: "She never goes to school late.",
    blankSentence: "She ___ goes to school late.",
    answer: "never",
    acceptableAnswers: ["never"],
    translation: "她上學從不遲到。",
    explanation: "never 表示從不，是頻率副詞。",
    category: "頻率副詞",
    hint: "表示從不",
  },
  {
    id: "blank-103",
    sentence: "We often play basketball after school.",
    blankSentence: "We ___ play basketball after school.",
    answer: "often",
    acceptableAnswers: ["often"],
    translation: "我們放學後常常打籃球。",
    explanation: "often 表示常常，是頻率副詞。",
    category: "頻率副詞",
    hint: "表示常常",
  },
  {
    id: "blank-104",
    sentence: "He sometimes reads comics.",
    blankSentence: "He ___ reads comics.",
    answer: "sometimes",
    acceptableAnswers: ["sometimes"],
    translation: "他有時候讀漫畫。",
    explanation: "sometimes 表示有時候，是頻率副詞。",
    category: "頻率副詞",
    hint: "表示有時候",
  },
  {
    id: "blank-105",
    sentence: "They always say thank you.",
    blankSentence: "They ___ say thank you.",
    answer: "always",
    acceptableAnswers: ["always"],
    translation: "他們總是說謝謝。",
    explanation: "always 表示總是，是頻率副詞。",
    category: "頻率副詞",
    hint: "表示總是",
  },
  {
    id: "blank-106",
    sentence: "There are many books in the library.",
    blankSentence: "There are ___ books in the library.",
    answer: "many",
    acceptableAnswers: ["many"],
    translation: "圖書館裡有很多書。",
    explanation: "many 修飾可數名詞複數 books。",
    category: "數量詞",
    hint: "修飾可數名詞複數，表示很多",
  },
  {
    id: "blank-107",
    sentence: "I have some water.",
    blankSentence: "I have ___ water.",
    answer: "some",
    acceptableAnswers: ["some"],
    translation: "我有一些水。",
    explanation: "some 可修飾不可數名詞 water，表示一些。",
    category: "數量詞",
    hint: "表示一些",
  },
  {
    id: "blank-108",
    sentence: "There is a little milk in the cup.",
    blankSentence: "There is ___ little milk in the cup.",
    answer: "a",
    acceptableAnswers: ["a"],
    translation: "杯子裡有一點牛奶。",
    explanation: "a little 修飾不可數名詞，表示一點。",
    category: "數量詞",
    hint: "a little 的第一個字",
  },
  {
    id: "blank-109",
    sentence: "I have a few friends in class.",
    blankSentence: "I have a ___ friends in class.",
    answer: "few",
    acceptableAnswers: ["few"],
    translation: "我班上有幾個朋友。",
    explanation: "a few 修飾可數名詞複數，表示幾個。",
    category: "數量詞",
    hint: "a few 的第二個字",
  },
  {
    id: "blank-110",
    sentence: "Do you have any questions?",
    blankSentence: "Do you have ___ questions?",
    answer: "any",
    acceptableAnswers: ["any"],
    translation: "你有任何問題嗎？",
    explanation: "any 常用在疑問句中，表示任何或一些。",
    category: "數量詞",
    hint: "疑問句中表示任何",
  },
  {
    id: "blank-111",
    sentence: "I like apples and bananas.",
    blankSentence: "I like apples ___ bananas.",
    answer: "and",
    acceptableAnswers: ["and"],
    translation: "我喜歡蘋果和香蕉。",
    explanation: "and 連接兩個並列的事物，表示和。",
    category: "連接詞",
    hint: "表示和",
  },
  {
    id: "blank-112",
    sentence: "I am tired but happy.",
    blankSentence: "I am tired ___ happy.",
    answer: "but",
    acceptableAnswers: ["but"],
    translation: "我很累但是很開心。",
    explanation: "but 表示但是，用來連接相反或轉折的想法。",
    category: "連接詞",
    hint: "表示但是",
  },
  {
    id: "blank-113",
    sentence: "You can have tea or coffee.",
    blankSentence: "You can have tea ___ coffee.",
    answer: "or",
    acceptableAnswers: ["or"],
    translation: "你可以喝茶或咖啡。",
    explanation: "or 表示或者，用來連接選項。",
    category: "連接詞",
    hint: "表示或者",
  },
  {
    id: "blank-114",
    sentence: "I stay home because it is raining.",
    blankSentence: "I stay home ___ it is raining.",
    answer: "because",
    acceptableAnswers: ["because"],
    translation: "因為下雨，所以我待在家。",
    explanation: "because 用來說明原因。",
    category: "連接詞",
    hint: "表示因為",
  },
  {
    id: "blank-115",
    sentence: "Wash your hands before you eat.",
    blankSentence: "Wash your hands ___ you eat.",
    answer: "before",
    acceptableAnswers: ["before"],
    translation: "吃東西前要洗手。",
    explanation: "before 表示在……之前，連接兩個動作。",
    category: "連接詞",
    hint: "表示在之前",
  },
  {
    id: "blank-116",
    sentence: "You can borrow my eraser.",
    blankSentence: "You ___ borrow my eraser.",
    answer: "can",
    acceptableAnswers: ["can"],
    translation: "你可以借我的橡皮擦。",
    explanation: "can 可表示可以或能夠，後面接原形動詞 borrow。",
    category: "助動詞",
    hint: "表示可以的助動詞",
  },
  {
    id: "blank-117",
    sentence: "We must finish our homework.",
    blankSentence: "We ___ finish our homework.",
    answer: "must",
    acceptableAnswers: ["must"],
    translation: "我們必須完成作業。",
    explanation: "must 表示必須，後面接原形動詞 finish。",
    category: "助動詞",
    hint: "表示必須的助動詞",
  },
  {
    id: "blank-118",
    sentence: "May I open the window?",
    blankSentence: "___ I open the window?",
    answer: "May",
    acceptableAnswers: ["may", "May"],
    translation: "我可以打開窗戶嗎？",
    explanation: "May I...? 是禮貌地詢問是否可以做某事的句型。",
    category: "助動詞",
    hint: "禮貌詢問允許時常用",
  },
  {
    id: "blank-119",
    sentence: "She should see a doctor.",
    blankSentence: "She ___ see a doctor.",
    answer: "should",
    acceptableAnswers: ["should"],
    translation: "她應該去看醫生。",
    explanation: "should 表示應該，常用來提出建議。",
    category: "助動詞",
    hint: "表示應該的助動詞",
  },
  {
    id: "blank-120",
    sentence: "I cannot find my key.",
    blankSentence: "I ___ find my key.",
    answer: "cannot",
    acceptableAnswers: ["cannot", "can't", "cant"],
    translation: "我找不到我的鑰匙。",
    explanation: "cannot 和 can't 都表示不能；這裡表示不能找到鑰匙。",
    category: "助動詞",
    hint: "can 的否定形式",
  },
];

window.fillBlankQuestions = fillBlankQuestions;
