const fillBlankQuestions = [
  {
    id: "blank-001",
    sentence: "I drink milk every morning.",
    blankSentence: "I drink ___ every morning.",
    answer: "milk",
    acceptableAnswers: ["milk"],
    translation: "我每天早上喝牛奶。",
    explanation: "milk 是初級常見單字，表示牛奶。",
    category: "單字",
    hint: "一種白色飲品",
  },
  {
    id: "blank-002",
    sentence: "She has a small dog.",
    blankSentence: "She has a small ___.",
    answer: "dog",
    acceptableAnswers: ["dog"],
    translation: "她有一隻小狗。",
    explanation: "dog 是常見動物單字，表示狗。",
    category: "單字",
    hint: "會汪汪叫的動物",
  },
  {
    id: "blank-003",
    sentence: "This is my book.",
    blankSentence: "This is my ___.",
    answer: "book",
    acceptableAnswers: ["book"],
    translation: "這是我的書。",
    explanation: "book 表示書，是學校與日常生活常用單字。",
    category: "單字",
    hint: "可以閱讀的東西",
  },
  {
    id: "blank-004",
    sentence: "We eat rice for lunch.",
    blankSentence: "We eat ___ for lunch.",
    answer: "rice",
    acceptableAnswers: ["rice"],
    translation: "我們午餐吃飯。",
    explanation: "rice 表示米飯，是食物類常見單字。",
    category: "單字",
    hint: "常見主食",
  },
  {
    id: "blank-005",
    sentence: "The sky is blue.",
    blankSentence: "The sky is ___.",
    answer: "blue",
    acceptableAnswers: ["blue"],
    translation: "天空是藍色的。",
    explanation: "blue 表示藍色，是基礎顏色單字。",
    category: "單字",
    hint: "天空常見的顏色",
  },
  {
    id: "blank-006",
    sentence: "They play soccer after school.",
    blankSentence: "They ___ soccer after school.",
    answer: "play",
    acceptableAnswers: ["play"],
    translation: "他們放學後踢足球。",
    explanation: "play 可搭配球類運動，例如 play soccer。",
    category: "動詞",
    hint: "做球類運動常用的動詞",
  },
  {
    id: "blank-007",
    sentence: "I read a book at night.",
    blankSentence: "I ___ a book at night.",
    answer: "read",
    acceptableAnswers: ["read"],
    translation: "我晚上讀一本書。",
    explanation: "read 表示閱讀，read a book 是常見用法。",
    category: "動詞",
    hint: "看書時做的動作",
  },
  {
    id: "blank-008",
    sentence: "We eat breakfast at seven.",
    blankSentence: "We ___ breakfast at seven.",
    answer: "eat",
    acceptableAnswers: ["eat", "have"],
    translation: "我們七點吃早餐。",
    explanation: "eat breakfast 表示吃早餐；have breakfast 也常用來表示吃早餐。",
    category: "動詞",
    hint: "吃東西的動作",
  },
  {
    id: "blank-009",
    sentence: "He likes English.",
    blankSentence: "He ___ English.",
    answer: "likes",
    acceptableAnswers: ["likes"],
    translation: "他喜歡英文。",
    explanation: "主詞 He 是第三人稱單數，現在式動詞 like 要加 s，變成 likes。",
    category: "動詞",
    hint: "like 的第三人稱單數現在式",
  },
  {
    id: "blank-010",
    sentence: "My mother cooks dinner.",
    blankSentence: "My mother ___ dinner.",
    answer: "cooks",
    acceptableAnswers: ["cooks"],
    translation: "我媽媽煮晚餐。",
    explanation: "主詞 My mother 是第三人稱單數，現在式動詞 cook 要加 s。",
    category: "動詞",
    hint: "cook 的第三人稱單數現在式",
  },
  {
    id: "blank-011",
    sentence: "She is a student.",
    blankSentence: "She ___ a student.",
    answer: "is",
    acceptableAnswers: ["is"],
    translation: "她是一名學生。",
    explanation: "主詞 She 搭配 be 動詞 is。",
    category: "be 動詞",
    hint: "She 搭配的 be 動詞",
  },
  {
    id: "blank-012",
    sentence: "I am happy.",
    blankSentence: "I ___ happy.",
    answer: "am",
    acceptableAnswers: ["am"],
    translation: "我很開心。",
    explanation: "主詞 I 搭配 be 動詞 am。",
    category: "be 動詞",
    hint: "I 搭配的 be 動詞",
  },
  {
    id: "blank-013",
    sentence: "They are friends.",
    blankSentence: "They ___ friends.",
    answer: "are",
    acceptableAnswers: ["are"],
    translation: "他們是朋友。",
    explanation: "主詞 They 是複數，搭配 be 動詞 are。",
    category: "be 動詞",
    hint: "They 搭配的 be 動詞",
  },
  {
    id: "blank-014",
    sentence: "It is sunny today.",
    blankSentence: "It ___ sunny today.",
    answer: "is",
    acceptableAnswers: ["is"],
    translation: "今天是晴天。",
    explanation: "描述天氣時常用 It is，加上天氣形容詞。",
    category: "be 動詞",
    hint: "It 搭配的 be 動詞",
  },
  {
    id: "blank-015",
    sentence: "You are my teacher.",
    blankSentence: "You ___ my teacher.",
    answer: "are",
    acceptableAnswers: ["are"],
    translation: "你是我的老師。",
    explanation: "主詞 You 搭配 be 動詞 are。",
    category: "be 動詞",
    hint: "You 搭配的 be 動詞",
  },
  {
    id: "blank-016",
    sentence: "The book is on the desk.",
    blankSentence: "The book is ___ the desk.",
    answer: "on",
    acceptableAnswers: ["on"],
    translation: "書在桌子上。",
    explanation: "on 表示在物體表面上。",
    category: "介系詞",
    hint: "表示在上面",
  },
  {
    id: "blank-017",
    sentence: "The cat is under the chair.",
    blankSentence: "The cat is ___ the chair.",
    answer: "under",
    acceptableAnswers: ["under"],
    translation: "貓在椅子下面。",
    explanation: "under 表示在某物下面。",
    category: "介系詞",
    hint: "表示在下面",
  },
  {
    id: "blank-018",
    sentence: "I live in Taipei.",
    blankSentence: "I live ___ Taipei.",
    answer: "in",
    acceptableAnswers: ["in"],
    translation: "我住在台北。",
    explanation: "live in 加上城市或地點，表示住在某地。",
    category: "介系詞",
    hint: "表示在某城市裡",
  },
  {
    id: "blank-019",
    sentence: "She goes to school.",
    blankSentence: "She goes ___ school.",
    answer: "to",
    acceptableAnswers: ["to"],
    translation: "她去學校。",
    explanation: "go to school 表示去上學或去學校。",
    category: "介系詞",
    hint: "go 後面常接的方向介系詞",
  },
  {
    id: "blank-020",
    sentence: "The store is near my house.",
    blankSentence: "The store is ___ my house.",
    answer: "near",
    acceptableAnswers: ["near"],
    translation: "那家商店在我家附近。",
    explanation: "near 表示在附近、靠近。",
    category: "介系詞",
    hint: "表示靠近",
  },
  {
    id: "blank-021",
    sentence: "What is your name?",
    blankSentence: "___ is your name?",
    answer: "What",
    acceptableAnswers: ["what", "What"],
    translation: "你的名字是什麼？",
    explanation: "What 用來詢問事物、名字或內容。",
    category: "疑問詞",
    hint: "詢問什麼",
  },
  {
    id: "blank-022",
    sentence: "Where do you live?",
    blankSentence: "___ do you live?",
    answer: "Where",
    acceptableAnswers: ["where", "Where"],
    translation: "你住在哪裡？",
    explanation: "Where 用來詢問地點。",
    category: "疑問詞",
    hint: "詢問地點",
  },
  {
    id: "blank-023",
    sentence: "Who is that boy?",
    blankSentence: "___ is that boy?",
    answer: "Who",
    acceptableAnswers: ["who", "Who"],
    translation: "那個男孩是誰？",
    explanation: "Who 用來詢問人物。",
    category: "疑問詞",
    hint: "詢問人物",
  },
  {
    id: "blank-024",
    sentence: "When is your birthday?",
    blankSentence: "___ is your birthday?",
    answer: "When",
    acceptableAnswers: ["when", "When"],
    translation: "你的生日是什麼時候？",
    explanation: "When 用來詢問時間。",
    category: "疑問詞",
    hint: "詢問時間",
  },
  {
    id: "blank-025",
    sentence: "How are you?",
    blankSentence: "___ are you?",
    answer: "How",
    acceptableAnswers: ["how", "How"],
    translation: "你好嗎？",
    explanation: "How are you? 是常見問候語。",
    category: "疑問詞",
    hint: "問候近況時使用",
  },
  {
    id: "blank-026",
    sentence: "I eat breakfast in the morning.",
    blankSentence: "I eat breakfast in the ___.",
    answer: "morning",
    acceptableAnswers: ["morning"],
    translation: "我在早上吃早餐。",
    explanation: "in the morning 表示在早上。",
    category: "時間",
    hint: "一天的開始時段",
  },
  {
    id: "blank-027",
    sentence: "We have lunch at noon.",
    blankSentence: "We have lunch at ___.",
    answer: "noon",
    acceptableAnswers: ["noon"],
    translation: "我們中午吃午餐。",
    explanation: "at noon 表示在中午。",
    category: "時間",
    hint: "中午十二點左右",
  },
  {
    id: "blank-028",
    sentence: "I go to bed at night.",
    blankSentence: "I go to bed at ___.",
    answer: "night",
    acceptableAnswers: ["night"],
    translation: "我晚上上床睡覺。",
    explanation: "at night 表示在晚上。",
    category: "時間",
    hint: "一天中天黑後的時間",
  },
  {
    id: "blank-029",
    sentence: "Today is Monday.",
    blankSentence: "Today is ___.",
    answer: "Monday",
    acceptableAnswers: ["monday", "Monday"],
    translation: "今天是星期一。",
    explanation: "Monday 表示星期一，星期名稱首字母通常大寫。",
    category: "時間",
    hint: "一週的第一個上課日",
  },
  {
    id: "blank-030",
    sentence: "My class starts at eight.",
    blankSentence: "My class starts at ___.",
    answer: "eight",
    acceptableAnswers: ["eight", "8"],
    translation: "我的課八點開始。",
    explanation: "eight 表示數字 8；時間也可簡寫成 8。",
    category: "時間",
    hint: "數字 8 的英文",
  },
  {
    id: "blank-031",
    sentence: "I go to school by bus.",
    blankSentence: "I go to school by ___.",
    answer: "bus",
    acceptableAnswers: ["bus"],
    translation: "我搭公車去上學。",
    explanation: "by bus 表示搭公車，是常見交通工具用法。",
    category: "交通",
    hint: "交通工具",
  },
  {
    id: "blank-032",
    sentence: "Tom rides a bike to the park.",
    blankSentence: "Tom rides a ___ to the park.",
    answer: "bike",
    acceptableAnswers: ["bike", "bicycle"],
    translation: "Tom 騎腳踏車去公園。",
    explanation: "bike 和 bicycle 都可以表示腳踏車。",
    category: "交通",
    hint: "兩輪交通工具",
  },
  {
    id: "blank-033",
    sentence: "My father drives a car.",
    blankSentence: "My father drives a ___.",
    answer: "car",
    acceptableAnswers: ["car"],
    translation: "我爸爸開車。",
    explanation: "drive a car 表示開車。",
    category: "交通",
    hint: "常見四輪交通工具",
  },
  {
    id: "blank-034",
    sentence: "We take the train to Tainan.",
    blankSentence: "We take the ___ to Tainan.",
    answer: "train",
    acceptableAnswers: ["train"],
    translation: "我們搭火車去台南。",
    explanation: "take the train 表示搭火車。",
    category: "交通",
    hint: "在鐵軌上行駛的交通工具",
  },
  {
    id: "blank-035",
    sentence: "The bus stop is near the school.",
    blankSentence: "The ___ stop is near the school.",
    answer: "bus",
    acceptableAnswers: ["bus"],
    translation: "公車站在學校附近。",
    explanation: "bus stop 表示公車站。",
    category: "交通",
    hint: "bus stop 的第一個字",
  },
  {
    id: "blank-036",
    sentence: "I brush my teeth every day.",
    blankSentence: "I brush my ___ every day.",
    answer: "teeth",
    acceptableAnswers: ["teeth"],
    translation: "我每天刷牙。",
    explanation: "brush my teeth 表示刷牙，teeth 是 tooth 的複數。",
    category: "日常生活",
    hint: "刷牙時清潔的部位",
  },
  {
    id: "blank-037",
    sentence: "She washes her hands before dinner.",
    blankSentence: "She washes her ___ before dinner.",
    answer: "hands",
    acceptableAnswers: ["hands"],
    translation: "她晚餐前洗手。",
    explanation: "wash hands 表示洗手，是日常生活常用語。",
    category: "日常生活",
    hint: "吃飯前常清洗的身體部位",
  },
  {
    id: "blank-038",
    sentence: "We watch TV after dinner.",
    blankSentence: "We watch ___ after dinner.",
    answer: "TV",
    acceptableAnswers: ["tv", "TV", "television"],
    translation: "我們晚餐後看電視。",
    explanation: "watch TV 表示看電視；TV 也可以寫成 television。",
    category: "日常生活",
    hint: "晚餐後常看的家電或節目",
  },
  {
    id: "blank-039",
    sentence: "I do my homework after school.",
    blankSentence: "I do my ___ after school.",
    answer: "homework",
    acceptableAnswers: ["homework"],
    translation: "我放學後做作業。",
    explanation: "do my homework 表示做我的作業。",
    category: "日常生活",
    hint: "學生放學後要完成的功課",
  },
  {
    id: "blank-040",
    sentence: "He cleans his room on Saturday.",
    blankSentence: "He cleans his ___ on Saturday.",
    answer: "room",
    acceptableAnswers: ["room"],
    translation: "他星期六打掃他的房間。",
    explanation: "clean one's room 表示打掃某人的房間。",
    category: "日常生活",
    hint: "睡覺或讀書的房間",
  },
];

window.fillBlankQuestions = fillBlankQuestions;
