const readingQuestions = [
  {
    id: "reading-001",
    title: "My School Day",
    level: "初級",
    category: "學校生活",
    passage: "I go to school from Monday to Friday. My school is near my home, so I walk there with my sister. In the morning, we study English, math, and science. At lunch, I eat with my friends. After class, I read books in the library. I like my school day because I can learn many new things.",
    translation: "我星期一到星期五去上學。我的學校離家很近，所以我和妹妹走路去。早上我們學英文、數學和自然。午餐時，我和朋友一起吃飯。下課後，我在圖書館看書。我喜歡上學日，因為我可以學到許多新事物。",
    questions: [
      {
        id: "reading-001-q1",
        question: "When does the student go to school?",
        options: ["From Monday to Friday", "Only on Sunday", "Every night", "In summer"],
        answer: "From Monday to Friday",
        explanation: "文章第一句說 I go to school from Monday to Friday。",
      },
      {
        id: "reading-001-q2",
        question: "How does the student go to school?",
        options: ["By train", "By bus", "On foot", "By bike"],
        answer: "On foot",
        explanation: "文章說學校很近，所以學生和妹妹 walk there，也就是走路去。",
      },
      {
        id: "reading-001-q3",
        question: "Why does the student like the school day?",
        options: ["Because the student can learn new things", "Because there is no class", "Because school is very far", "Because lunch is at home"],
        answer: "Because the student can learn new things",
        explanation: "最後一句說喜歡上學日，因為可以 learn many new things。",
      },
    ],
  },
  {
    id: "reading-002",
    title: "My Family Dinner",
    level: "初級",
    category: "家庭",
    passage: "Every evening, my family has dinner together. My father cooks rice and fish. My mother makes a small salad. My brother sets the table, and I put water in the cups. We talk about our day while we eat. After dinner, we wash the dishes together. Dinner time is simple, but it makes our family feel close.",
    translation: "每天晚上，我的家人一起吃晚餐。爸爸煮飯和魚。媽媽做一份小沙拉。哥哥擺餐具，我把水倒進杯子裡。我們一邊吃飯一邊聊一天的事情。晚餐後，我們一起洗碗。晚餐時間很簡單，但讓我們家感覺很親近。",
    questions: [
      {
        id: "reading-002-q1",
        question: "What does the father cook?",
        options: ["Rice and fish", "Noodles and eggs", "Bread and soup", "Chicken and cake"],
        answer: "Rice and fish",
        explanation: "文章說 My father cooks rice and fish。",
      },
      {
        id: "reading-002-q2",
        question: "What does the writer do before dinner?",
        options: ["Puts water in the cups", "Buys a salad", "Washes the car", "Reads a story"],
        answer: "Puts water in the cups",
        explanation: "文章說 I put water in the cups。",
      },
      {
        id: "reading-002-q3",
        question: "What is the main idea of the passage?",
        options: ["A family enjoys dinner together", "A boy eats lunch at school", "A mother goes shopping", "A brother plays sports"],
        answer: "A family enjoys dinner together",
        explanation: "整篇文章都在描述一家人一起準備、吃晚餐和收拾。",
      },
    ],
  },
  {
    id: "reading-003",
    title: "A Healthy Breakfast",
    level: "初級",
    category: "食物",
    passage: "Mia likes breakfast because it gives her energy for school. She usually eats an egg, some fruit, and a piece of bread. She drinks milk, too. On busy mornings, she still tries to eat something before she leaves home. Her teacher says a healthy breakfast helps students listen well in class. Mia feels ready after breakfast.",
    translation: "Mia 喜歡早餐，因為早餐給她上學的能量。她通常吃一顆蛋、一些水果和一片麵包。她也喝牛奶。在忙碌的早晨，她仍然試著在離家前吃點東西。她的老師說健康的早餐能幫助學生在課堂上專心聽講。Mia 吃完早餐後覺得準備好了。",
    questions: [
      {
        id: "reading-003-q1",
        question: "Why does Mia like breakfast?",
        options: ["It gives her energy", "It makes her late", "It is always candy", "It is after school"],
        answer: "It gives her energy",
        explanation: "文章第一句說早餐 gives her energy for school。",
      },
      {
        id: "reading-003-q2",
        question: "What does Mia usually drink?",
        options: ["Milk", "Tea", "Juice", "Coffee"],
        answer: "Milk",
        explanation: "文章說 She drinks milk, too。",
      },
      {
        id: "reading-003-q3",
        question: "What does the word 'healthy' mean in this passage?",
        options: ["Good for the body", "Very late", "Hard to find", "Full of toys"],
        answer: "Good for the body",
        explanation: "文中 healthy breakfast 能幫助學生上課專心，表示對身體有益。",
      },
    ],
  },
  {
    id: "reading-004",
    title: "Basketball After School",
    level: "初級",
    category: "運動",
    passage: "Ben plays basketball after school on Wednesdays. He meets three classmates at the park. They practice passing the ball and taking shots. Ben is not the tallest player, but he runs fast and listens to his coach. When the game ends, the team drinks water and rests. Ben enjoys basketball because it is fun and helps him stay strong.",
    translation: "Ben 每週三放學後打籃球。他在公園和三位同學見面。他們練習傳球和投籃。Ben 不是最高的球員，但他跑得快，也聽教練的話。比賽結束時，隊伍喝水休息。Ben 喜歡籃球，因為籃球很有趣，也幫助他保持強壯。",
    questions: [
      {
        id: "reading-004-q1",
        question: "When does Ben play basketball?",
        options: ["On Wednesdays after school", "Every morning", "On Sunday night", "Before breakfast"],
        answer: "On Wednesdays after school",
        explanation: "文章第一句說 Ben plays basketball after school on Wednesdays。",
      },
      {
        id: "reading-004-q2",
        question: "Where does Ben meet his classmates?",
        options: ["At the park", "At the library", "At a store", "At the station"],
        answer: "At the park",
        explanation: "文章說 He meets three classmates at the park。",
      },
      {
        id: "reading-004-q3",
        question: "Which sentence is true about Ben?",
        options: ["He runs fast", "He hates basketball", "He never drinks water", "He is the coach"],
        answer: "He runs fast",
        explanation: "文章說 Ben is not the tallest player, but he runs fast。",
      },
    ],
  },
  {
    id: "reading-005",
    title: "A New Friend",
    level: "初級",
    category: "朋友",
    passage: "Lily is new in class. At first, she is quiet because she does not know anyone. During art class, Jack shares his colored pencils with her. They draw a picture of a sunny park. Lily smiles and thanks him. At lunch, Jack asks Lily to sit with his friends. Lily feels happy because she has a new friend.",
    translation: "Lily 是班上的新同學。一開始她很安靜，因為她不認識任何人。在美術課時，Jack 和她分享他的色鉛筆。他們畫了一張陽光公園的圖。Lily 微笑並謝謝他。午餐時，Jack 請 Lily 和他的朋友坐在一起。Lily 覺得很開心，因為她有了一位新朋友。",
    questions: [
      {
        id: "reading-005-q1",
        question: "Why is Lily quiet at first?",
        options: ["She does not know anyone", "She is sleeping", "She loses her lunch", "She dislikes art"],
        answer: "She does not know anyone",
        explanation: "文章說她一開始 quiet，because she does not know anyone。",
      },
      {
        id: "reading-005-q2",
        question: "What does Jack share with Lily?",
        options: ["Colored pencils", "A basketball", "A sandwich", "A phone"],
        answer: "Colored pencils",
        explanation: "文章說 Jack shares his colored pencils with her。",
      },
      {
        id: "reading-005-q3",
        question: "How does Lily feel at the end?",
        options: ["Happy", "Angry", "Tired", "Afraid"],
        answer: "Happy",
        explanation: "最後一句說 Lily feels happy because she has a new friend。",
      },
    ],
  },
  {
    id: "reading-006",
    title: "A Trip to Tainan",
    level: "初級",
    category: "旅行",
    passage: "Last Saturday, Kevin took a train to Tainan with his parents. They visited an old street and saw many small shops. Kevin bought a postcard for his teacher. In the afternoon, they ate warm beef soup and sweet fruit. Kevin took many photos with his phone. He wants to visit Tainan again during winter vacation.",
    translation: "上週六，Kevin 和父母搭火車去台南。他們參觀一條老街，看見許多小店。Kevin 買了一張明信片給老師。下午，他們吃了熱牛肉湯和甜水果。Kevin 用手機拍了許多照片。他想在寒假再去台南。",
    questions: [
      {
        id: "reading-006-q1",
        question: "How did Kevin go to Tainan?",
        options: ["By train", "By plane", "By boat", "By bike"],
        answer: "By train",
        explanation: "文章第一句說 Kevin took a train to Tainan。",
      },
      {
        id: "reading-006-q2",
        question: "What did Kevin buy?",
        options: ["A postcard", "A hat", "A toy train", "A map"],
        answer: "A postcard",
        explanation: "文章說 Kevin bought a postcard for his teacher。",
      },
      {
        id: "reading-006-q3",
        question: "What does Kevin want to do?",
        options: ["Visit Tainan again", "Move to Tainan tomorrow", "Stop taking photos", "Eat only bread"],
        answer: "Visit Tainan again",
        explanation: "最後一句說 He wants to visit Tainan again。",
      },
    ],
  },
  {
    id: "reading-007",
    title: "A Rainy Morning",
    level: "初級",
    category: "天氣",
    passage: "It is raining when Amy wakes up. She looks out the window and sees dark clouds. Amy wears a yellow raincoat and takes an umbrella. On the way to school, she walks slowly because the ground is wet. Her shoes get a little dirty, but she stays dry. In class, Amy draws a picture of the rainy morning.",
    translation: "Amy 醒來時正在下雨。她看向窗外，看見烏雲。Amy 穿上黃色雨衣並帶了一把雨傘。去學校的路上，她走得很慢，因為地面是濕的。她的鞋子有點髒，但她保持乾爽。在課堂上，Amy 畫了一張雨天早晨的圖。",
    questions: [
      {
        id: "reading-007-q1",
        question: "What is the weather like in the morning?",
        options: ["Rainy", "Sunny", "Snowy", "Windy and hot"],
        answer: "Rainy",
        explanation: "文章第一句說 It is raining when Amy wakes up。",
      },
      {
        id: "reading-007-q2",
        question: "What color is Amy's raincoat?",
        options: ["Yellow", "Blue", "Green", "Black"],
        answer: "Yellow",
        explanation: "文章說 Amy wears a yellow raincoat。",
      },
      {
        id: "reading-007-q3",
        question: "Why does Amy walk slowly?",
        options: ["The ground is wet", "She is reading", "Her school is closed", "The sun is too bright"],
        answer: "The ground is wet",
        explanation: "文章說她走得慢 because the ground is wet。",
      },
    ],
  },
  {
    id: "reading-008",
    title: "Grandma's Birthday",
    level: "初級",
    category: "生日",
    passage: "Today is Grandma's birthday. Nora and her family visit Grandma in the afternoon. Nora brings a handmade card with flowers on it. Her father buys a small cake, and her mother prepares tea. Everyone sings a birthday song. Grandma closes her eyes and makes a wish. She says the best gift is seeing the whole family together.",
    translation: "今天是奶奶的生日。Nora 和家人在下午去拜訪奶奶。Nora 帶了一張有花朵圖案的手作卡片。她的爸爸買了一個小蛋糕，媽媽準備茶。大家唱生日歌。奶奶閉上眼睛許願。她說最好的禮物是看見全家人在一起。",
    questions: [
      {
        id: "reading-008-q1",
        question: "What does Nora bring to Grandma?",
        options: ["A handmade card", "A big clock", "A red bag", "A new chair"],
        answer: "A handmade card",
        explanation: "文章說 Nora brings a handmade card with flowers on it。",
      },
      {
        id: "reading-008-q2",
        question: "Who buys a small cake?",
        options: ["Nora's father", "Nora's teacher", "Grandma", "Nora's brother"],
        answer: "Nora's father",
        explanation: "文章說 Her father buys a small cake。",
      },
      {
        id: "reading-008-q3",
        question: "What is Grandma's best gift?",
        options: ["Seeing the whole family together", "Having many toys", "Getting a new phone", "Eating breakfast alone"],
        answer: "Seeing the whole family together",
        explanation: "最後一句說最好的禮物是 seeing the whole family together。",
      },
    ],
  },
  {
    id: "reading-009",
    title: "At the Market",
    level: "初級",
    category: "購物",
    passage: "Sam goes to the market with his aunt on Sunday. They need apples, tomatoes, and eggs. Sam carries a small basket. His aunt checks the prices before she buys food. A friendly seller gives Sam one orange to try. It is sweet. Sam learns that shopping can be fun when he helps and listens carefully.",
    translation: "Sam 星期日和阿姨去市場。他們需要蘋果、番茄和蛋。Sam 提著一個小籃子。阿姨在買食物前會查看價格。一位友善的攤販給 Sam 一顆橘子試吃。橘子很甜。Sam 學到當他幫忙並仔細聽時，購物也可以很有趣。",
    questions: [
      {
        id: "reading-009-q1",
        question: "Where does Sam go on Sunday?",
        options: ["To the market", "To the beach", "To the zoo", "To the hospital"],
        answer: "To the market",
        explanation: "文章第一句說 Sam goes to the market with his aunt on Sunday。",
      },
      {
        id: "reading-009-q2",
        question: "What does Sam carry?",
        options: ["A small basket", "A heavy desk", "A school bag", "A blue umbrella"],
        answer: "A small basket",
        explanation: "文章說 Sam carries a small basket。",
      },
      {
        id: "reading-009-q3",
        question: "What does the seller give Sam?",
        options: ["One orange", "Three eggs", "A tomato plant", "A toy car"],
        answer: "One orange",
        explanation: "文章說 A friendly seller gives Sam one orange to try。",
      },
    ],
  },
  {
    id: "reading-010",
    title: "Our Weekend Park",
    level: "初級",
    category: "週末活動",
    passage: "On weekends, Eric and his cousin often go to a park near their homes. They ride bikes on the path and watch birds in the trees. Sometimes they bring sandwiches and have lunch under a big tree. Before they leave, they pick up their trash. Eric likes the park because it is clean, quiet, and full of green plants.",
    translation: "週末時，Eric 和表弟常去家附近的公園。他們在小路上騎腳踏車，也看樹上的鳥。有時他們帶三明治，在一棵大樹下吃午餐。離開前，他們撿起自己的垃圾。Eric 喜歡這座公園，因為它乾淨、安靜，而且有許多綠色植物。",
    questions: [
      {
        id: "reading-010-q1",
        question: "What do Eric and his cousin ride?",
        options: ["Bikes", "Horses", "Trains", "Boats"],
        answer: "Bikes",
        explanation: "文章說 They ride bikes on the path。",
      },
      {
        id: "reading-010-q2",
        question: "Where do they sometimes eat lunch?",
        options: ["Under a big tree", "Inside a bus", "At school", "In a bookstore"],
        answer: "Under a big tree",
        explanation: "文章說他們 sometimes bring sandwiches and have lunch under a big tree。",
      },
      {
        id: "reading-010-q3",
        question: "Why does Eric like the park?",
        options: ["It is clean, quiet, and green", "It is loud and dirty", "It has no trees", "It is far from home"],
        answer: "It is clean, quiet, and green",
        explanation: "最後一句說公園 clean, quiet, and full of green plants。",
      },
    ],
  },
];

window.readingQuestions = readingQuestions;
