const articleQuestions = [
  {
    id: "article-001",
    sentence: "I have a book.",
    blankSentence: "I have ___ book.",
    options: ["a", "an", "the", "不填"],
    answer: "a",
    explanation: "book 是單數可數名詞，第一次提到，且 book 的發音不是母音開頭，所以用 a。",
    category: "a",
  },
  {
    id: "article-002",
    sentence: "He is a teacher.",
    blankSentence: "He is ___ teacher.",
    options: ["a", "an", "the", "不填"],
    answer: "a",
    explanation: "teacher 是單數可數名詞，用來說明他的身分，且發音不是母音開頭，所以用 a。",
    category: "a",
  },
  {
    id: "article-003",
    sentence: "She has a cat.",
    blankSentence: "She has ___ cat.",
    options: ["a", "an", "the", "不填"],
    answer: "a",
    explanation: "cat 是單數可數名詞，第一次提到，且 cat 的發音不是母音開頭，所以用 a。",
    category: "a",
  },
  {
    id: "article-004",
    sentence: "This is a pencil.",
    blankSentence: "This is ___ pencil.",
    options: ["a", "an", "the", "不填"],
    answer: "a",
    explanation: "pencil 是單數可數名詞，第一次提到，且 pencil 的發音不是母音開頭，所以用 a。",
    category: "a",
  },
  {
    id: "article-005",
    sentence: "Tom wants a banana.",
    blankSentence: "Tom wants ___ banana.",
    options: ["a", "an", "the", "不填"],
    answer: "a",
    explanation: "banana 是單數可數名詞，第一次提到，且 banana 的發音不是母音開頭，所以用 a。",
    category: "a",
  },
  {
    id: "article-006",
    sentence: "We see a bus.",
    blankSentence: "We see ___ bus.",
    options: ["a", "an", "the", "不填"],
    answer: "a",
    explanation: "bus 是單數可數名詞，第一次提到，且 bus 的發音不是母音開頭，所以用 a。",
    category: "a",
  },
  {
    id: "article-007",
    sentence: "My brother has a bike.",
    blankSentence: "My brother has ___ bike.",
    options: ["a", "an", "the", "不填"],
    answer: "a",
    explanation: "bike 是單數可數名詞，第一次提到，且 bike 的發音不是母音開頭，所以用 a。",
    category: "a",
  },
  {
    id: "article-008",
    sentence: "There is a park near my house.",
    blankSentence: "There is ___ park near my house.",
    options: ["a", "an", "the", "不填"],
    answer: "a",
    explanation: "park 是單數可數名詞，第一次介紹某個公園，且 park 的發音不是母音開頭，所以用 a。",
    category: "a",
  },
  {
    id: "article-009",
    sentence: "She eats an apple.",
    blankSentence: "She eats ___ apple.",
    options: ["a", "an", "the", "不填"],
    answer: "an",
    explanation: "apple 是單數可數名詞，第一次提到，且 apple 的發音是母音開頭，所以用 an。",
    category: "an",
  },
  {
    id: "article-010",
    sentence: "This is an egg.",
    blankSentence: "This is ___ egg.",
    options: ["a", "an", "the", "不填"],
    answer: "an",
    explanation: "egg 是單數可數名詞，第一次提到，且 egg 的發音是母音開頭，所以用 an。",
    category: "an",
  },
  {
    id: "article-011",
    sentence: "He has an umbrella.",
    blankSentence: "He has ___ umbrella.",
    options: ["a", "an", "the", "不填"],
    answer: "an",
    explanation: "umbrella 是單數可數名詞，第一次提到，且 umbrella 的發音是母音開頭，所以用 an。",
    category: "an",
  },
  {
    id: "article-012",
    sentence: "I need an eraser.",
    blankSentence: "I need ___ eraser.",
    options: ["a", "an", "the", "不填"],
    answer: "an",
    explanation: "eraser 是單數可數名詞，第一次提到，且 eraser 的發音是母音開頭，所以用 an。",
    category: "an",
  },
  {
    id: "article-013",
    sentence: "Amy sees an elephant.",
    blankSentence: "Amy sees ___ elephant.",
    options: ["a", "an", "the", "不填"],
    answer: "an",
    explanation: "elephant 是單數可數名詞，第一次提到，且 elephant 的發音是母音開頭，所以用 an。",
    category: "an",
  },
  {
    id: "article-014",
    sentence: "It is an orange.",
    blankSentence: "It is ___ orange.",
    options: ["a", "an", "the", "不填"],
    answer: "an",
    explanation: "orange 是單數可數名詞，第一次提到，且 orange 的發音是母音開頭，所以用 an。",
    category: "an",
  },
  {
    id: "article-015",
    sentence: "This is an old house.",
    blankSentence: "This is ___ old house.",
    options: ["a", "an", "the", "不填"],
    answer: "an",
    explanation: "old 的發音是母音開頭，後面接單數可數名詞 house，所以用 an old house。",
    category: "an",
  },
  {
    id: "article-016",
    sentence: "The sun is hot.",
    blankSentence: "___ sun is hot.",
    options: ["a", "an", "the", "不填"],
    answer: "the",
    explanation: "sun 是大家都知道的特定事物，通常用 the sun。",
    category: "the",
  },
  {
    id: "article-017",
    sentence: "Please open the door.",
    blankSentence: "Please open ___ door.",
    options: ["a", "an", "the", "不填"],
    answer: "the",
    explanation: "說話者和聽話者知道是哪一扇門，所以 door 是特定的，用 the。",
    category: "the",
  },
  {
    id: "article-018",
    sentence: "The moon is bright.",
    blankSentence: "___ moon is bright.",
    options: ["a", "an", "the", "不填"],
    answer: "the",
    explanation: "moon 是大家都知道的特定事物，通常用 the moon。",
    category: "the",
  },
  {
    id: "article-019",
    sentence: "I see a dog. The dog is black.",
    blankSentence: "I see a dog. ___ dog is black.",
    options: ["a", "an", "the", "不填"],
    answer: "the",
    explanation: "dog 前面已經提過，第二次提到同一隻狗時，用 the。",
    category: "the",
  },
  {
    id: "article-020",
    sentence: "The boy is my brother.",
    blankSentence: "___ boy is my brother.",
    options: ["a", "an", "the", "不填"],
    answer: "the",
    explanation: "這裡指特定的男孩，所以用 the boy。",
    category: "the",
  },
  {
    id: "article-021",
    sentence: "The water in this cup is cold.",
    blankSentence: "___ water in this cup is cold.",
    options: ["a", "an", "the", "不填"],
    answer: "the",
    explanation: "in this cup 說明是哪一杯水，是特定的水，所以用 the。",
    category: "the",
  },
  {
    id: "article-022",
    sentence: "Close the window, please.",
    blankSentence: "Close ___ window, please.",
    options: ["a", "an", "the", "不填"],
    answer: "the",
    explanation: "說話時通常知道要關哪一扇窗戶，所以 window 是特定的，用 the。",
    category: "the",
  },
  {
    id: "article-023",
    sentence: "The teacher is in the classroom.",
    blankSentence: "___ teacher is in the classroom.",
    options: ["a", "an", "the", "不填"],
    answer: "the",
    explanation: "這裡指特定的老師，所以用 the teacher。",
    category: "the",
  },
  {
    id: "article-024",
    sentence: "I like music.",
    blankSentence: "I like ___ music.",
    options: ["a", "an", "the", "不填"],
    answer: "不填",
    explanation: "music 是不可數名詞，泛指音樂時通常不加冠詞。",
    category: "不填",
  },
  {
    id: "article-025",
    sentence: "Dogs are friendly.",
    blankSentence: "___ dogs are friendly.",
    options: ["a", "an", "the", "不填"],
    answer: "不填",
    explanation: "dogs 是複數名詞，泛指狗這種動物時通常不加冠詞。",
    category: "不填",
  },
  {
    id: "article-026",
    sentence: "We play baseball after school.",
    blankSentence: "We play ___ baseball after school.",
    options: ["a", "an", "the", "不填"],
    answer: "不填",
    explanation: "球類運動 baseball 前面通常不加冠詞。",
    category: "不填",
  },
  {
    id: "article-027",
    sentence: "She drinks milk every morning.",
    blankSentence: "She drinks ___ milk every morning.",
    options: ["a", "an", "the", "不填"],
    answer: "不填",
    explanation: "milk 是不可數名詞，泛指牛奶時通常不加冠詞。",
    category: "不填",
  },
  {
    id: "article-028",
    sentence: "Cats like fish.",
    blankSentence: "___ cats like fish.",
    options: ["a", "an", "the", "不填"],
    answer: "不填",
    explanation: "cats 是複數名詞，泛指貓這種動物時通常不加冠詞。",
    category: "不填",
  },
  {
    id: "article-029",
    sentence: "I eat rice for lunch.",
    blankSentence: "I eat ___ rice for lunch.",
    options: ["a", "an", "the", "不填"],
    answer: "不填",
    explanation: "rice 是不可數名詞，泛指米飯時通常不加冠詞。",
    category: "不填",
  },
  {
    id: "article-030",
    sentence: "Children need water.",
    blankSentence: "Children need ___ water.",
    options: ["a", "an", "the", "不填"],
    answer: "不填",
    explanation: "water 是不可數名詞，泛指水時通常不加冠詞。",
    category: "不填",
  },
];

window.articleQuestions = articleQuestions;
