const geptVocabulary = [
  {
    word: "apple",
    partOfSpeech: "noun",
    meaning: "蘋果",
    category: "食物飲料",
    example: "I eat an apple every day.",
    translation: "我每天吃一顆蘋果。",
  },
  {
    word: "book",
    partOfSpeech: "noun",
    meaning: "書；書本",
    category: "物品用品",
    example: "This book is very interesting.",
    translation: "這本書很有趣。",
  },
  {
    word: "school",
    partOfSpeech: "noun",
    meaning: "學校",
    category: "學校生活",
    example: "My school is near the park.",
    translation: "我的學校在公園附近。",
  },
  {
    word: "teacher",
    partOfSpeech: "noun",
    meaning: "老師",
    category: "人物家庭",
    example: "Our teacher is kind to every student.",
    translation: "我們的老師對每位學生都很親切。",
  },
  {
    word: "student",
    partOfSpeech: "noun",
    meaning: "學生",
    category: "學校生活",
    example: "The student reads English after class.",
    translation: "那位學生下課後讀英文。",
  },
  {
    word: "friend",
    partOfSpeech: "noun",
    meaning: "朋友",
    category: "人物家庭",
    example: "I play basketball with my friend.",
    translation: "我和朋友一起打籃球。",
  },
  {
    word: "family",
    partOfSpeech: "noun",
    meaning: "家人；家庭",
    category: "人物家庭",
    example: "My family has dinner together every night.",
    translation: "我的家人每天晚上一起吃晚餐。",
  },
  {
    word: "water",
    partOfSpeech: "noun",
    meaning: "水",
    category: "食物飲料",
    example: "Please drink some water.",
    translation: "請喝一些水。",
  },
  {
    word: "food",
    partOfSpeech: "noun",
    meaning: "食物",
    category: "食物飲料",
    example: "Taiwan has a lot of good food.",
    translation: "台灣有很多好吃的食物。",
  },
  {
    word: "breakfast",
    partOfSpeech: "noun",
    meaning: "早餐",
    category: "食物飲料",
    example: "I usually eat breakfast at seven.",
    translation: "我通常七點吃早餐。",
  },
  {
    word: "lunch",
    partOfSpeech: "noun",
    meaning: "午餐",
    category: "食物飲料",
    example: "We have lunch at school.",
    translation: "我們在學校吃午餐。",
  },
  {
    word: "dinner",
    partOfSpeech: "noun",
    meaning: "晚餐",
    category: "食物飲料",
    example: "Dad cooks dinner on Sunday.",
    translation: "爸爸星期日煮晚餐。",
  },
  {
    word: "happy",
    partOfSpeech: "adjective",
    meaning: "快樂的；高興的",
    category: "常用形容詞",
    example: "She is happy to see her friend.",
    translation: "她很高興見到她的朋友。",
  },
  {
    word: "sad",
    partOfSpeech: "adjective",
    meaning: "難過的",
    category: "常用形容詞",
    example: "The boy feels sad today.",
    translation: "那個男孩今天覺得難過。",
  },
  {
    word: "big",
    partOfSpeech: "adjective",
    meaning: "大的",
    category: "常用形容詞",
    example: "They live in a big house.",
    translation: "他們住在一棟大房子裡。",
  },
  {
    word: "small",
    partOfSpeech: "adjective",
    meaning: "小的",
    category: "常用形容詞",
    example: "The small dog runs fast.",
    translation: "那隻小狗跑得很快。",
  },
  {
    word: "good",
    partOfSpeech: "adjective",
    meaning: "好的",
    category: "常用形容詞",
    example: "This is a good idea.",
    translation: "這是一個好主意。",
  },
  {
    word: "bad",
    partOfSpeech: "adjective",
    meaning: "壞的；不好的",
    category: "常用形容詞",
    example: "The weather is bad today.",
    translation: "今天天氣不好。",
  },
  {
    word: "go",
    partOfSpeech: "verb",
    meaning: "去",
    category: "地點交通",
    example: "We go to the library after school.",
    translation: "我們放學後去圖書館。",
  },
  {
    word: "come",
    partOfSpeech: "verb",
    meaning: "來",
    category: "常用動詞",
    example: "Please come here and sit down.",
    translation: "請來這裡坐下。",
  },
  {
    word: "eat",
    partOfSpeech: "verb",
    meaning: "吃",
    category: "食物飲料",
    example: "I eat lunch with my classmates.",
    translation: "我和同學一起吃午餐。",
  },
  {
    word: "drink",
    partOfSpeech: "verb",
    meaning: "喝",
    category: "食物飲料",
    example: "Do you drink milk every morning?",
    translation: "你每天早上喝牛奶嗎？",
  },
  {
    word: "read",
    partOfSpeech: "verb",
    meaning: "閱讀；讀",
    category: "學校生活",
    example: "He likes to read storybooks.",
    translation: "他喜歡讀故事書。",
  },
  {
    word: "write",
    partOfSpeech: "verb",
    meaning: "寫",
    category: "學校生活",
    example: "Please write your name on the paper.",
    translation: "請把你的名字寫在紙上。",
  },
  {
    word: "listen",
    partOfSpeech: "verb",
    meaning: "聽",
    category: "學校生活",
    example: "The students listen to the teacher.",
    translation: "學生們聽老師說話。",
  },
  {
    word: "speak",
    partOfSpeech: "verb",
    meaning: "說；說話",
    category: "學校生活",
    example: "Can you speak English?",
    translation: "你會說英文嗎？",
  },
  {
    word: "play",
    partOfSpeech: "verb",
    meaning: "玩；打（球）；演奏",
    category: "運動休閒",
    example: "Children play in the park.",
    translation: "孩子們在公園裡玩。",
  },
  {
    word: "study",
    partOfSpeech: "verb",
    meaning: "學習；讀書",
    category: "學校生活",
    example: "I study English for thirty minutes every day.",
    translation: "我每天讀三十分鐘英文。",
  },
  {
    word: "like",
    partOfSpeech: "verb",
    meaning: "喜歡",
    category: "常用動詞",
    example: "They like music and movies.",
    translation: "他們喜歡音樂和電影。",
  },
  {
    word: "want",
    partOfSpeech: "verb",
    meaning: "想要",
    category: "常用動詞",
    example: "I want a glass of water.",
    translation: "我想要一杯水。",
  },
  {
    word: "father",
    partOfSpeech: "noun",
    meaning: "父親；爸爸",
    category: "人物家庭",
    example: "My father drives me to school.",
    translation: "我爸爸開車載我去學校。",
  },
  {
    word: "mother",
    partOfSpeech: "noun",
    meaning: "母親；媽媽",
    category: "人物家庭",
    example: "My mother makes breakfast.",
    translation: "我媽媽做早餐。",
  },
  {
    word: "brother",
    partOfSpeech: "noun",
    meaning: "兄弟",
    category: "人物家庭",
    example: "My brother is ten years old.",
    translation: "我弟弟十歲。",
  },
  {
    word: "sister",
    partOfSpeech: "noun",
    meaning: "姊妹",
    category: "人物家庭",
    example: "Her sister likes to draw.",
    translation: "她的姊姊喜歡畫畫。",
  },
  {
    word: "parent",
    partOfSpeech: "noun",
    meaning: "父親或母親；家長",
    category: "人物家庭",
    example: "Each parent signs the note.",
    translation: "每位家長在通知單上簽名。",
  },
  {
    word: "child",
    partOfSpeech: "noun",
    meaning: "小孩",
    category: "人物家庭",
    example: "The child smiles at the dog.",
    translation: "那個小孩對狗微笑。",
  },
  {
    word: "classmate",
    partOfSpeech: "noun",
    meaning: "同班同學",
    category: "人物家庭",
    example: "My classmate helps me after class.",
    translation: "我的同學下課後幫助我。",
  },
  {
    word: "classroom",
    partOfSpeech: "noun",
    meaning: "教室",
    category: "學校生活",
    example: "Our classroom is clean.",
    translation: "我們的教室很乾淨。",
  },
  {
    word: "homework",
    partOfSpeech: "noun",
    meaning: "家庭作業",
    category: "學校生活",
    example: "I finish my homework before dinner.",
    translation: "我在晚餐前完成作業。",
  },
  {
    word: "test",
    partOfSpeech: "noun",
    meaning: "考試；測驗",
    category: "學校生活",
    example: "We have a math test today.",
    translation: "我們今天有數學考試。",
  },
  {
    word: "milk",
    partOfSpeech: "noun",
    meaning: "牛奶",
    category: "食物飲料",
    example: "She drinks milk every morning.",
    translation: "她每天早上喝牛奶。",
  },
  {
    word: "rice",
    partOfSpeech: "noun",
    meaning: "米飯",
    category: "食物飲料",
    example: "We eat rice for dinner.",
    translation: "我們晚餐吃飯。",
  },
  {
    word: "home",
    partOfSpeech: "noun",
    meaning: "家",
    category: "日常生活",
    example: "I go home after school.",
    translation: "我放學後回家。",
  },
  {
    word: "house",
    partOfSpeech: "noun",
    meaning: "房子",
    category: "日常生活",
    example: "Their house has a small garden.",
    translation: "他們的房子有一個小花園。",
  },
  {
    word: "room",
    partOfSpeech: "noun",
    meaning: "房間",
    category: "日常生活",
    example: "My room is bright.",
    translation: "我的房間很明亮。",
  },
  {
    word: "bed",
    partOfSpeech: "noun",
    meaning: "床",
    category: "日常生活",
    example: "The cat sleeps on the bed.",
    translation: "那隻貓睡在床上。",
  },
  {
    word: "bath",
    partOfSpeech: "noun",
    meaning: "洗澡",
    category: "日常生活",
    example: "I take a bath at night.",
    translation: "我晚上洗澡。",
  },
  {
    word: "clothes",
    partOfSpeech: "noun",
    meaning: "衣服",
    category: "日常生活",
    example: "These clothes are clean.",
    translation: "這些衣服很乾淨。",
  },
  {
    word: "morning",
    partOfSpeech: "noun",
    meaning: "早上",
    category: "日常生活",
    example: "I brush my teeth in the morning.",
    translation: "我早上刷牙。",
  },
  {
    word: "night",
    partOfSpeech: "noun",
    meaning: "夜晚；晚上",
    category: "日常生活",
    example: "We read a story at night.",
    translation: "我們晚上讀故事。",
  },
  {
    word: "wash",
    partOfSpeech: "verb",
    meaning: "洗",
    category: "日常生活",
    example: "Please wash your hands.",
    translation: "請洗你的手。",
  },
  {
    word: "sleep",
    partOfSpeech: "verb",
    meaning: "睡覺",
    category: "日常生活",
    example: "The baby sleeps well.",
    translation: "那個嬰兒睡得很好。",
  },
  {
    word: "make",
    partOfSpeech: "verb",
    meaning: "製作；使成為",
    category: "常用動詞",
    example: "We make cards for Mom.",
    translation: "我們做卡片給媽媽。",
  },
  {
    word: "take",
    partOfSpeech: "verb",
    meaning: "拿；搭乘",
    category: "常用動詞",
    example: "Please take this book.",
    translation: "請拿這本書。",
  },
  {
    word: "give",
    partOfSpeech: "verb",
    meaning: "給",
    category: "常用動詞",
    example: "I give my friend a pencil.",
    translation: "我給朋友一枝鉛筆。",
  },
  {
    word: "help",
    partOfSpeech: "verb",
    meaning: "幫助",
    category: "常用動詞",
    example: "Can you help me?",
    translation: "你可以幫我嗎？",
  },
  {
    word: "see",
    partOfSpeech: "verb",
    meaning: "看見",
    category: "常用動詞",
    example: "I see a bird in the tree.",
    translation: "我看見樹上有一隻鳥。",
  },
  {
    word: "find",
    partOfSpeech: "verb",
    meaning: "找到",
    category: "常用動詞",
    example: "She finds her keys.",
    translation: "她找到她的鑰匙。",
  },
  {
    word: "open",
    partOfSpeech: "verb",
    meaning: "打開",
    category: "常用動詞",
    example: "Please open the door.",
    translation: "請打開門。",
  },
  {
    word: "new",
    partOfSpeech: "adjective",
    meaning: "新的",
    category: "常用形容詞",
    example: "I have a new bag.",
    translation: "我有一個新書包。",
  },
  {
    word: "old",
    partOfSpeech: "adjective",
    meaning: "舊的；年老的",
    category: "常用形容詞",
    example: "This old bike is blue.",
    translation: "這台舊腳踏車是藍色的。",
  },
  {
    word: "hot",
    partOfSpeech: "adjective",
    meaning: "熱的",
    category: "常用形容詞",
    example: "The soup is hot.",
    translation: "湯很熱。",
  },
  {
    word: "cold",
    partOfSpeech: "adjective",
    meaning: "冷的",
    category: "常用形容詞",
    example: "The water is cold.",
    translation: "水很冷。",
  },
  {
    word: "today",
    partOfSpeech: "noun",
    meaning: "今天",
    category: "時間天氣",
    example: "Today is Monday.",
    translation: "今天是星期一。",
  },
  {
    word: "tomorrow",
    partOfSpeech: "noun",
    meaning: "明天",
    category: "時間天氣",
    example: "Tomorrow is my birthday.",
    translation: "明天是我的生日。",
  },
  {
    word: "yesterday",
    partOfSpeech: "noun",
    meaning: "昨天",
    category: "時間天氣",
    example: "Yesterday was sunny.",
    translation: "昨天是晴天。",
  },
  {
    word: "week",
    partOfSpeech: "noun",
    meaning: "星期；週",
    category: "時間天氣",
    example: "We have music class this week.",
    translation: "我們這週有音樂課。",
  },
  {
    word: "month",
    partOfSpeech: "noun",
    meaning: "月份；月",
    category: "時間天氣",
    example: "June is a hot month.",
    translation: "六月是炎熱的月份。",
  },
  {
    word: "year",
    partOfSpeech: "noun",
    meaning: "年",
    category: "時間天氣",
    example: "A year has twelve months.",
    translation: "一年有十二個月。",
  },
  {
    word: "sunny",
    partOfSpeech: "adjective",
    meaning: "晴朗的",
    category: "時間天氣",
    example: "It is sunny today.",
    translation: "今天是晴天。",
  },
  {
    word: "rainy",
    partOfSpeech: "adjective",
    meaning: "下雨的；多雨的",
    category: "時間天氣",
    example: "It is rainy in the afternoon.",
    translation: "下午下雨。",
  },
  {
    word: "cloudy",
    partOfSpeech: "adjective",
    meaning: "多雲的",
    category: "時間天氣",
    example: "The sky is cloudy now.",
    translation: "現在天空多雲。",
  },
  {
    word: "windy",
    partOfSpeech: "adjective",
    meaning: "有風的",
    category: "時間天氣",
    example: "It is windy near the sea.",
    translation: "海邊風很大。",
  },
  {
    word: "park",
    partOfSpeech: "noun",
    meaning: "公園",
    category: "地點交通",
    example: "We walk in the park.",
    translation: "我們在公園散步。",
  },
  {
    word: "library",
    partOfSpeech: "noun",
    meaning: "圖書館",
    category: "地點交通",
    example: "The library is quiet.",
    translation: "圖書館很安靜。",
  },
  {
    word: "store",
    partOfSpeech: "noun",
    meaning: "商店",
    category: "地點交通",
    example: "Mom goes to the store.",
    translation: "媽媽去商店。",
  },
  {
    word: "hospital",
    partOfSpeech: "noun",
    meaning: "醫院",
    category: "地點交通",
    example: "The hospital is on this street.",
    translation: "醫院在這條街上。",
  },
  {
    word: "street",
    partOfSpeech: "noun",
    meaning: "街道",
    category: "地點交通",
    example: "The street is busy.",
    translation: "這條街很忙碌。",
  },
  {
    word: "bus",
    partOfSpeech: "noun",
    meaning: "公車",
    category: "地點交通",
    example: "I go to school by bus.",
    translation: "我搭公車去學校。",
  },
  {
    word: "car",
    partOfSpeech: "noun",
    meaning: "汽車",
    category: "地點交通",
    example: "That car is white.",
    translation: "那台汽車是白色的。",
  },
  {
    word: "bike",
    partOfSpeech: "noun",
    meaning: "腳踏車",
    category: "地點交通",
    example: "He rides a bike to the park.",
    translation: "他騎腳踏車去公園。",
  },
  {
    word: "train",
    partOfSpeech: "noun",
    meaning: "火車",
    category: "地點交通",
    example: "The train is fast.",
    translation: "火車很快。",
  },
  {
    word: "bag",
    partOfSpeech: "noun",
    meaning: "袋子；包包",
    category: "物品用品",
    example: "This bag is heavy.",
    translation: "這個包包很重。",
  },
  {
    word: "pen",
    partOfSpeech: "noun",
    meaning: "筆",
    category: "物品用品",
    example: "I write with a pen.",
    translation: "我用筆寫字。",
  },
  {
    word: "pencil",
    partOfSpeech: "noun",
    meaning: "鉛筆",
    category: "物品用品",
    example: "The pencil is on the desk.",
    translation: "鉛筆在桌上。",
  },
  {
    word: "paper",
    partOfSpeech: "noun",
    meaning: "紙",
    category: "物品用品",
    example: "Please give me some paper.",
    translation: "請給我一些紙。",
  },
  {
    word: "desk",
    partOfSpeech: "noun",
    meaning: "書桌；課桌",
    category: "物品用品",
    example: "My desk is near the window.",
    translation: "我的書桌在窗戶旁邊。",
  },
  {
    word: "chair",
    partOfSpeech: "noun",
    meaning: "椅子",
    category: "物品用品",
    example: "Please sit on the chair.",
    translation: "請坐在椅子上。",
  },
  {
    word: "phone",
    partOfSpeech: "noun",
    meaning: "電話；手機",
    category: "物品用品",
    example: "My phone is in my bag.",
    translation: "我的手機在包包裡。",
  },
  {
    word: "key",
    partOfSpeech: "noun",
    meaning: "鑰匙",
    category: "物品用品",
    example: "This key opens the door.",
    translation: "這把鑰匙可以打開門。",
  },
  {
    word: "umbrella",
    partOfSpeech: "noun",
    meaning: "雨傘",
    category: "物品用品",
    example: "Take an umbrella on rainy days.",
    translation: "下雨天帶一把雨傘。",
  },
  {
    word: "basketball",
    partOfSpeech: "noun",
    meaning: "籃球",
    category: "運動休閒",
    example: "We play basketball after school.",
    translation: "我們放學後打籃球。",
  },
  {
    word: "baseball",
    partOfSpeech: "noun",
    meaning: "棒球",
    category: "運動休閒",
    example: "He likes baseball very much.",
    translation: "他非常喜歡棒球。",
  },
  {
    word: "soccer",
    partOfSpeech: "noun",
    meaning: "足球",
    category: "運動休閒",
    example: "They play soccer on Sunday.",
    translation: "他們星期日踢足球。",
  },
  {
    word: "swim",
    partOfSpeech: "verb",
    meaning: "游泳",
    category: "運動休閒",
    example: "I can swim in the pool.",
    translation: "我會在游泳池游泳。",
  },
  {
    word: "run",
    partOfSpeech: "verb",
    meaning: "跑",
    category: "運動休閒",
    example: "The boys run fast.",
    translation: "男孩們跑得很快。",
  },
  {
    word: "walk",
    partOfSpeech: "verb",
    meaning: "走路；散步",
    category: "運動休閒",
    example: "We walk to school.",
    translation: "我們走路去學校。",
  },
  {
    word: "music",
    partOfSpeech: "noun",
    meaning: "音樂",
    category: "運動休閒",
    example: "I listen to music at home.",
    translation: "我在家聽音樂。",
  },
  {
    word: "movie",
    partOfSpeech: "noun",
    meaning: "電影",
    category: "運動休閒",
    example: "This movie is funny.",
    translation: "這部電影很好笑。",
  },
  {
    word: "game",
    partOfSpeech: "noun",
    meaning: "遊戲；比賽",
    category: "運動休閒",
    example: "The game starts at two.",
    translation: "比賽兩點開始。",
  },
];
