const geptVocabulary = [
  {
    word: "apple",
    partOfSpeech: "noun",
    meaning: "蘋果",
    example: "I eat an apple every day.",
    translation: "我每天吃一顆蘋果。",
  },
  {
    word: "book",
    partOfSpeech: "noun",
    meaning: "書；書本",
    example: "This book is very interesting.",
    translation: "這本書很有趣。",
  },
  {
    word: "school",
    partOfSpeech: "noun",
    meaning: "學校",
    example: "My school is near the park.",
    translation: "我的學校在公園附近。",
  },
  {
    word: "teacher",
    partOfSpeech: "noun",
    meaning: "老師",
    example: "Our teacher is kind to every student.",
    translation: "我們的老師對每位學生都很親切。",
  },
  {
    word: "student",
    partOfSpeech: "noun",
    meaning: "學生",
    example: "The student reads English after class.",
    translation: "那位學生下課後讀英文。",
  },
  {
    word: "friend",
    partOfSpeech: "noun",
    meaning: "朋友",
    example: "I play basketball with my friend.",
    translation: "我和朋友一起打籃球。",
  },
  {
    word: "family",
    partOfSpeech: "noun",
    meaning: "家人；家庭",
    example: "My family has dinner together every night.",
    translation: "我的家人每天晚上一起吃晚餐。",
  },
  {
    word: "water",
    partOfSpeech: "noun",
    meaning: "水",
    example: "Please drink some water.",
    translation: "請喝一些水。",
  },
  {
    word: "food",
    partOfSpeech: "noun",
    meaning: "食物",
    example: "Taiwan has a lot of good food.",
    translation: "台灣有很多好吃的食物。",
  },
  {
    word: "breakfast",
    partOfSpeech: "noun",
    meaning: "早餐",
    example: "I usually eat breakfast at seven.",
    translation: "我通常七點吃早餐。",
  },
  {
    word: "lunch",
    partOfSpeech: "noun",
    meaning: "午餐",
    example: "We have lunch at school.",
    translation: "我們在學校吃午餐。",
  },
  {
    word: "dinner",
    partOfSpeech: "noun",
    meaning: "晚餐",
    example: "Dad cooks dinner on Sunday.",
    translation: "爸爸星期日煮晚餐。",
  },
  {
    word: "happy",
    partOfSpeech: "adjective",
    meaning: "快樂的；高興的",
    example: "She is happy to see her friend.",
    translation: "她很高興見到她的朋友。",
  },
  {
    word: "sad",
    partOfSpeech: "adjective",
    meaning: "難過的",
    example: "The boy feels sad today.",
    translation: "那個男孩今天覺得難過。",
  },
  {
    word: "big",
    partOfSpeech: "adjective",
    meaning: "大的",
    example: "They live in a big house.",
    translation: "他們住在一棟大房子裡。",
  },
  {
    word: "small",
    partOfSpeech: "adjective",
    meaning: "小的",
    example: "The small dog runs fast.",
    translation: "那隻小狗跑得很快。",
  },
  {
    word: "good",
    partOfSpeech: "adjective",
    meaning: "好的",
    example: "This is a good idea.",
    translation: "這是一個好主意。",
  },
  {
    word: "bad",
    partOfSpeech: "adjective",
    meaning: "壞的；不好的",
    example: "The weather is bad today.",
    translation: "今天天氣不好。",
  },
  {
    word: "go",
    partOfSpeech: "verb",
    meaning: "去",
    example: "We go to the library after school.",
    translation: "我們放學後去圖書館。",
  },
  {
    word: "come",
    partOfSpeech: "verb",
    meaning: "來",
    example: "Please come here and sit down.",
    translation: "請來這裡坐下。",
  },
  {
    word: "eat",
    partOfSpeech: "verb",
    meaning: "吃",
    example: "I eat lunch with my classmates.",
    translation: "我和同學一起吃午餐。",
  },
  {
    word: "drink",
    partOfSpeech: "verb",
    meaning: "喝",
    example: "Do you drink milk every morning?",
    translation: "你每天早上喝牛奶嗎？",
  },
  {
    word: "read",
    partOfSpeech: "verb",
    meaning: "閱讀；讀",
    example: "He likes to read storybooks.",
    translation: "他喜歡讀故事書。",
  },
  {
    word: "write",
    partOfSpeech: "verb",
    meaning: "寫",
    example: "Please write your name on the paper.",
    translation: "請把你的名字寫在紙上。",
  },
  {
    word: "listen",
    partOfSpeech: "verb",
    meaning: "聽",
    example: "The students listen to the teacher.",
    translation: "學生們聽老師說話。",
  },
  {
    word: "speak",
    partOfSpeech: "verb",
    meaning: "說；說話",
    example: "Can you speak English?",
    translation: "你會說英文嗎？",
  },
  {
    word: "play",
    partOfSpeech: "verb",
    meaning: "玩；打（球）；演奏",
    example: "Children play in the park.",
    translation: "孩子們在公園裡玩。",
  },
  {
    word: "study",
    partOfSpeech: "verb",
    meaning: "學習；讀書",
    example: "I study English for thirty minutes every day.",
    translation: "我每天讀三十分鐘英文。",
  },
  {
    word: "like",
    partOfSpeech: "verb",
    meaning: "喜歡",
    example: "They like music and movies.",
    translation: "他們喜歡音樂和電影。",
  },
  {
    word: "want",
    partOfSpeech: "verb",
    meaning: "想要",
    example: "I want a glass of water.",
    translation: "我想要一杯水。",
  },
];
